/**
 * Deterministic WeeklyConceptPack generator — the module's session-generator
 * entry point (SessionGeneratorDescriptor kind 'weekly-pack-generator').
 *
 * `generatePack(level, week, packSeed, contentVersion)` is a PURE function:
 * packs are never stored; `bb_week_state.pack_seed` + `content_version` are
 * the regeneration inputs (increment-1 handoff / DD15 versioned pointers).
 *
 * Resolution order:
 *  1. Fixture loader — the spec's three worked packs (A15, B14, D17) are
 *     served verbatim for their (level, week); they are static, so the seed
 *     does not vary their surface, and they stay pinned at their authored
 *     contentVersion (1.0.0).
 *  2. Seeded week templates — increment-2 seed content covers the natural
 *     post-placement entry weeks: A1, A2, B1, B2, C1, C2.
 */

import type { BBLevel, PackDay, ParentSummarySeed, WeeklyConceptPack } from '../types';
import { getFixture, FIXTURE_WEEKS } from './fixtures';
// <<< WEEK IMPORTS (generated by scripts/bb-wire-weeks.ts) >>>
import { buildA01 } from './templates/weeks/a01';
import { buildA02 } from './templates/weeks/a02';
import { buildA03 } from './templates/weeks/a03';
import { buildA04 } from './templates/weeks/a04';
import { buildA05 } from './templates/weeks/a05';
import { buildA06 } from './templates/weeks/a06';
import { buildA07 } from './templates/weeks/a07';
import { buildA08 } from './templates/weeks/a08';
import { buildA09 } from './templates/weeks/a09';
import { buildA10 } from './templates/weeks/a10';
import { buildA11 } from './templates/weeks/a11';
import { buildA12 } from './templates/weeks/a12';
import { buildA13 } from './templates/weeks/a13';
import { buildA14 } from './templates/weeks/a14';
import { buildA16 } from './templates/weeks/a16';
import { buildA17 } from './templates/weeks/a17';
import { buildA18 } from './templates/weeks/a18';
import { buildA19 } from './templates/weeks/a19';
import { buildA20 } from './templates/weeks/a20';
import { buildA21 } from './templates/weeks/a21';
import { buildA22 } from './templates/weeks/a22';
import { buildA23 } from './templates/weeks/a23';
import { buildA24 } from './templates/weeks/a24';
import { buildB01 } from './templates/weeks/b01';
import { buildB02 } from './templates/weeks/b02';
import { buildB03 } from './templates/weeks/b03';
import { buildB04 } from './templates/weeks/b04';
import { buildB05 } from './templates/weeks/b05';
import { buildB06 } from './templates/weeks/b06';
import { buildB07 } from './templates/weeks/b07';
import { buildB08 } from './templates/weeks/b08';
import { buildB09 } from './templates/weeks/b09';
import { buildB10 } from './templates/weeks/b10';
import { buildB11 } from './templates/weeks/b11';
import { buildB12 } from './templates/weeks/b12';
import { buildB13 } from './templates/weeks/b13';
import { buildB14 } from './templates/weeks/b14';
import { buildB15 } from './templates/weeks/b15';
import { buildB16 } from './templates/weeks/b16';
import { buildB17 } from './templates/weeks/b17';
import { buildB18 } from './templates/weeks/b18';
import { buildB19 } from './templates/weeks/b19';
import { buildB20 } from './templates/weeks/b20';
import { buildB21 } from './templates/weeks/b21';
import { buildB22 } from './templates/weeks/b22';
import { buildB23 } from './templates/weeks/b23';
import { buildB24 } from './templates/weeks/b24';
import { buildC01 } from './templates/weeks/c01';
import { buildC02 } from './templates/weeks/c02';
import { buildC03 } from './templates/weeks/c03';
import { buildC04 } from './templates/weeks/c04';
import { buildC05 } from './templates/weeks/c05';
import { buildC06 } from './templates/weeks/c06';
import { buildC07 } from './templates/weeks/c07';
import { buildC08 } from './templates/weeks/c08';
import { buildC09 } from './templates/weeks/c09';
import { buildC10 } from './templates/weeks/c10';
import { buildC11 } from './templates/weeks/c11';
import { buildC12 } from './templates/weeks/c12';
import { buildC13 } from './templates/weeks/c13';
import { buildC14 } from './templates/weeks/c14';
import { buildC15 } from './templates/weeks/c15';
import { buildC16 } from './templates/weeks/c16';
import { buildC17 } from './templates/weeks/c17';
import { buildC18 } from './templates/weeks/c18';
import { buildC19 } from './templates/weeks/c19';
import { buildC20 } from './templates/weeks/c20';
import { buildC21 } from './templates/weeks/c21';
import { buildC22 } from './templates/weeks/c22';
import { buildC23 } from './templates/weeks/c23';
import { buildC24 } from './templates/weeks/c24';
import { buildD01 } from './templates/weeks/d01';
import { buildD02 } from './templates/weeks/d02';
import { buildD03 } from './templates/weeks/d03';
import { buildD04 } from './templates/weeks/d04';
import { buildD05 } from './templates/weeks/d05';
import { buildD06 } from './templates/weeks/d06';
import { buildD07 } from './templates/weeks/d07';
import { buildD08 } from './templates/weeks/d08';
import { buildD09 } from './templates/weeks/d09';
import { buildD10 } from './templates/weeks/d10';
import { buildD11 } from './templates/weeks/d11';
import { buildD12 } from './templates/weeks/d12';
import { buildD13 } from './templates/weeks/d13';
import { buildD14 } from './templates/weeks/d14';
import { buildD15 } from './templates/weeks/d15';
import { buildD16 } from './templates/weeks/d16';
import { buildD17 } from './templates/weeks/d17';
import { buildD18 } from './templates/weeks/d18';
import { buildD19 } from './templates/weeks/d19';
import { buildD20 } from './templates/weeks/d20';
import { buildD21 } from './templates/weeks/d21';
import { buildD22 } from './templates/weeks/d22';
import { buildD23 } from './templates/weeks/d23';
import { buildD24 } from './templates/weeks/d24';
import { buildE01 } from './templates/weeks/e01';
import { buildE02 } from './templates/weeks/e02';
import { buildE03 } from './templates/weeks/e03';
import { buildE04 } from './templates/weeks/e04';
import { buildE05 } from './templates/weeks/e05';
import { buildE06 } from './templates/weeks/e06';
import { buildE07 } from './templates/weeks/e07';
import { buildE08 } from './templates/weeks/e08';
import { buildE09 } from './templates/weeks/e09';
import { buildE10 } from './templates/weeks/e10';
import { buildE11 } from './templates/weeks/e11';
import { buildE12 } from './templates/weeks/e12';
import { buildE13 } from './templates/weeks/e13';
import { buildE14 } from './templates/weeks/e14';
import { buildE15 } from './templates/weeks/e15';
import { buildE16 } from './templates/weeks/e16';
import { buildE17 } from './templates/weeks/e17';
import { buildE21 } from './templates/weeks/e21';
import { buildE22 } from './templates/weeks/e22';
import { buildE23 } from './templates/weeks/e23';
import { buildE24 } from './templates/weeks/e24';
// <<< END WEEK IMPORTS >>>

/**
 * Default content version stamped on template-generated packs.
 * 1.1.0 — LS1-R4 retrieval ramp (see applyRetrievalRamp). Learners pinned at
 * 1.0.0 keep regenerating their original packs (DD15 versioned pointers).
 * 1.2.0 — the B0 SURFACE-REALISM pass: currency and grammar rendered through
 *   lib/format.ts, context-sensitive fraction simplification, cross-week context
 *   rotation, warm-up format variety, thousands separators, and the pedagogy
 *   lifts (eliciting metacognition, claim-only error analysis, signal fade).
 *   Surfaces CHANGE deliberately at this bump — a given pack_seed renders
 *   different prose than it did at 1.1.0, while every computed answer is
 *   unchanged. Determinism is re-established at the new content.
 */
export { CONTENT_VERSION } from '../contentVersion';
import { CONTENT_VERSION } from '../contentVersion';
import { restampPageCounts } from '../session/dayFlow';

type WeekBuilder = (packSeed: number, contentVersion: string) => WeeklyConceptPack;

const WEEK_BUILDERS: ReadonlyMap<string, WeekBuilder> = new Map<string, WeekBuilder>([
// <<< WEEK BUILDERS (generated by scripts/bb-wire-weeks.ts) >>>
  ['A1', buildA01],
  ['A2', buildA02],
  ['A3', buildA03],
  ['A4', buildA04],
  ['A5', buildA05],
  ['A6', buildA06],
  ['A7', buildA07],
  ['A8', buildA08],
  ['A9', buildA09],
  ['A10', buildA10],
  ['A11', buildA11],
  ['A12', buildA12],
  ['A13', buildA13],
  ['A14', buildA14],
  ['A16', buildA16],
  ['A17', buildA17],
  ['A18', buildA18],
  ['A19', buildA19],
  ['A20', buildA20],
  ['A21', buildA21],
  ['A22', buildA22],
  ['A23', buildA23],
  ['A24', buildA24],
  ['B1', buildB01],
  ['B2', buildB02],
  ['B3', buildB03],
  ['B4', buildB04],
  ['B5', buildB05],
  ['B6', buildB06],
  ['B7', buildB07],
  ['B8', buildB08],
  ['B9', buildB09],
  ['B10', buildB10],
  ['B11', buildB11],
  ['B12', buildB12],
  ['B13', buildB13],
  ['B14', buildB14],
  ['B15', buildB15],
  ['B16', buildB16],
  ['B17', buildB17],
  ['B18', buildB18],
  ['B19', buildB19],
  ['B20', buildB20],
  ['B21', buildB21],
  ['B22', buildB22],
  ['B23', buildB23],
  ['B24', buildB24],
  ['C1', buildC01],
  ['C2', buildC02],
  ['C3', buildC03],
  ['C4', buildC04],
  ['C5', buildC05],
  ['C6', buildC06],
  ['C7', buildC07],
  ['C8', buildC08],
  ['C9', buildC09],
  ['C10', buildC10],
  ['C11', buildC11],
  ['C12', buildC12],
  ['C13', buildC13],
  ['C14', buildC14],
  ['C15', buildC15],
  ['C16', buildC16],
  ['C17', buildC17],
  ['C18', buildC18],
  ['C19', buildC19],
  ['C20', buildC20],
  ['C21', buildC21],
  ['C22', buildC22],
  ['C23', buildC23],
  ['C24', buildC24],
  ['D1', buildD01],
  ['D2', buildD02],
  ['D3', buildD03],
  ['D4', buildD04],
  ['D5', buildD05],
  ['D6', buildD06],
  ['D7', buildD07],
  ['D8', buildD08],
  ['D9', buildD09],
  ['D10', buildD10],
  ['D11', buildD11],
  ['D12', buildD12],
  ['D13', buildD13],
  ['D14', buildD14],
  ['D15', buildD15],
  ['D16', buildD16],
  ['D17', buildD17],
  ['D18', buildD18],
  ['D19', buildD19],
  ['D20', buildD20],
  ['D21', buildD21],
  ['D22', buildD22],
  ['D23', buildD23],
  ['D24', buildD24],
  ['E1', buildE01],
  ['E2', buildE02],
  ['E3', buildE03],
  ['E4', buildE04],
  ['E5', buildE05],
  ['E6', buildE06],
  ['E7', buildE07],
  ['E8', buildE08],
  ['E9', buildE09],
  ['E10', buildE10],
  ['E11', buildE11],
  ['E12', buildE12],
  ['E13', buildE13],
  ['E14', buildE14],
  ['E15', buildE15],
  ['E16', buildE16],
  ['E17', buildE17],
  ['E21', buildE21],
  ['E22', buildE22],
  ['E23', buildE23],
  ['E24', buildE24],
// <<< END WEEK BUILDERS >>>
]);

/**
 * Weeks migrated to the v2 pedagogy contract (CONTENT-GENERATOR-FIX-SPEC §2).
 * The correctness gate passes `contract:'v2'` to `validatePack` for these so the
 * QG-11 embedded-claim DETECTOR blocks; v1 weeks + fixtures stay report-only.
 * Kept in lock-step with each blueprint's `pedagogyContract:'v2'` as weeks migrate.
 */
export const V2_WEEKS: ReadonlySet<string> = new Set<string>([
// <<< V2 WEEKS (generated by scripts/bb-wire-weeks.ts) >>>
  'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12',
  'A13', 'A14', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'B3',
  'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B10', 'B11', 'B12', 'B13', 'B14', 'B15',
  'B16', 'B17', 'B18', 'B19', 'B20', 'B21', 'B22', 'B23', 'B24', 'C1', 'C2', 'C3',
  'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15',
  'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'D1', 'D2', 'D3',
  'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15',
  'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'E1', 'E2', 'E3',
  'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15',
  'E16', 'E17', 'E21', 'E22', 'E23', 'E24',
// <<< END V2 WEEKS >>>
]);

/** (level, week) cells generated from seeded templates. */
export const GENERATED_WEEKS: ReadonlyArray<{ level: BBLevel; week: number }> = [
// <<< GENERATED WEEKS (generated by scripts/bb-wire-weeks.ts) >>>
  { level: 'A', week: 1 },
  { level: 'A', week: 2 },
  { level: 'A', week: 3 },
  { level: 'A', week: 4 },
  { level: 'A', week: 5 },
  { level: 'A', week: 6 },
  { level: 'A', week: 7 },
  { level: 'A', week: 8 },
  { level: 'A', week: 9 },
  { level: 'A', week: 10 },
  { level: 'A', week: 11 },
  { level: 'A', week: 12 },
  { level: 'A', week: 13 },
  { level: 'A', week: 14 },
  { level: 'A', week: 16 },
  { level: 'A', week: 17 },
  { level: 'A', week: 18 },
  { level: 'A', week: 19 },
  { level: 'A', week: 20 },
  { level: 'A', week: 21 },
  { level: 'A', week: 22 },
  { level: 'A', week: 23 },
  { level: 'A', week: 24 },
  { level: 'B', week: 1 },
  { level: 'B', week: 2 },
  { level: 'B', week: 3 },
  { level: 'B', week: 4 },
  { level: 'B', week: 5 },
  { level: 'B', week: 6 },
  { level: 'B', week: 7 },
  { level: 'B', week: 8 },
  { level: 'B', week: 9 },
  { level: 'B', week: 10 },
  { level: 'B', week: 11 },
  { level: 'B', week: 12 },
  { level: 'B', week: 13 },
  { level: 'B', week: 15 },
  { level: 'B', week: 16 },
  { level: 'B', week: 17 },
  { level: 'B', week: 18 },
  { level: 'B', week: 19 },
  { level: 'B', week: 20 },
  { level: 'B', week: 21 },
  { level: 'B', week: 22 },
  { level: 'B', week: 23 },
  { level: 'B', week: 24 },
  { level: 'C', week: 1 },
  { level: 'C', week: 2 },
  { level: 'C', week: 3 },
  { level: 'C', week: 4 },
  { level: 'C', week: 5 },
  { level: 'C', week: 6 },
  { level: 'C', week: 7 },
  { level: 'C', week: 8 },
  { level: 'C', week: 9 },
  { level: 'C', week: 10 },
  { level: 'C', week: 11 },
  { level: 'C', week: 12 },
  { level: 'C', week: 13 },
  { level: 'C', week: 14 },
  { level: 'C', week: 15 },
  { level: 'C', week: 16 },
  { level: 'C', week: 17 },
  { level: 'C', week: 18 },
  { level: 'C', week: 19 },
  { level: 'C', week: 20 },
  { level: 'C', week: 21 },
  { level: 'C', week: 22 },
  { level: 'C', week: 23 },
  { level: 'C', week: 24 },
  { level: 'D', week: 1 },
  { level: 'D', week: 2 },
  { level: 'D', week: 3 },
  { level: 'D', week: 4 },
  { level: 'D', week: 5 },
  { level: 'D', week: 6 },
  { level: 'D', week: 7 },
  { level: 'D', week: 8 },
  { level: 'D', week: 9 },
  { level: 'D', week: 10 },
  { level: 'D', week: 11 },
  { level: 'D', week: 12 },
  { level: 'D', week: 13 },
  { level: 'D', week: 14 },
  { level: 'D', week: 15 },
  { level: 'D', week: 16 },
  { level: 'D', week: 17 },
  { level: 'D', week: 18 },
  { level: 'D', week: 19 },
  { level: 'D', week: 20 },
  { level: 'D', week: 21 },
  { level: 'D', week: 22 },
  { level: 'D', week: 23 },
  { level: 'D', week: 24 },
  { level: 'E', week: 1 },
  { level: 'E', week: 2 },
  { level: 'E', week: 3 },
  { level: 'E', week: 4 },
  { level: 'E', week: 5 },
  { level: 'E', week: 6 },
  { level: 'E', week: 7 },
  { level: 'E', week: 8 },
  { level: 'E', week: 9 },
  { level: 'E', week: 10 },
  { level: 'E', week: 11 },
  { level: 'E', week: 12 },
  { level: 'E', week: 13 },
  { level: 'E', week: 14 },
  { level: 'E', week: 15 },
  { level: 'E', week: 16 },
  { level: 'E', week: 17 },
  { level: 'E', week: 21 },
  { level: 'E', week: 22 },
  { level: 'E', week: 23 },
  { level: 'E', week: 24 },
// <<< END GENERATED WEEKS >>>
];

/** All (level, week) cells with servable content (templates + fixtures). */
export const AVAILABLE_WEEKS: ReadonlyArray<{ level: BBLevel; week: number; source: 'template' | 'fixture' }> = [
  ...GENERATED_WEEKS.map((w) => ({ ...w, source: 'template' as const })),
  ...FIXTURE_WEEKS.map((w) => ({ ...w, source: 'fixture' as const })),
];

/**
 * Cells with an authored builder that a pinned fixture SHADOWS — the builder is
 * registered and type-checked, but `generatePack` returns the fixture, so these
 * weeks are served to nobody.
 *
 * Exported because they were invisible: every gate enumerates AVAILABLE_WEEKS
 * (which reports the fixture) or GENERATED_WEEKS (which excludes them), so
 * `weeks/b14.ts` sat unvalidated from the day it was written. `bb-verify-packs`
 * now runs the full template battery over this list via `buildShadowedPack`.
 */
export const SHADOWED_WEEKS: ReadonlyArray<{ level: BBLevel; week: number }> = [...WEEK_BUILDERS.keys()]
  .map((key) => {
    const m = key.match(/^([A-E])(\d+)$/);
    return m ? { level: m[1] as BBLevel, week: Number(m[2]) } : null;
  })
  .filter((w): w is { level: BBLevel; week: number } => w !== null)
  .filter((w) => getFixture(w.level, w.week) !== undefined);

/**
 * Generate the pack a cell's BUILDER produces, bypassing the fixture loader.
 * Only for gates auditing a shadowed builder — child-facing code must use
 * `generatePack`, which honours the fixture.
 */
export function buildShadowedPack(
  level: BBLevel,
  week: number,
  packSeed: number,
  contentVersion: string = CONTENT_VERSION,
): WeeklyConceptPack {
  const builder = WEEK_BUILDERS.get(`${level}${week}`);
  if (!builder) throw new Error(`No builder registered for ${level} week ${week}`);
  const pack = builder(packSeed, contentVersion);
  if (versionAtLeast(contentVersion, 1, 1)) applyRetrievalRamp(pack);
  // Pages are counted from the FINAL day contents — after the ramp, never inside a builder.
  restampPageCounts(pack);
  return pack;
}

export function hasPackContent(level: BBLevel, week: number): boolean {
  return WEEK_BUILDERS.has(`${level}${week}`) || getFixture(level, week) !== undefined;
}

/**
 * Generate the WeeklyConceptPack for a curriculum cell.
 *
 * Deterministic: same (level, week, packSeed, contentVersion) → deep-equal
 * pack. Fixture-backed cells ignore packSeed/contentVersion (static, pinned).
 *
 * @throws when no content exists for (level, week) yet.
 */
export function generatePack(
  level: BBLevel,
  week: number,
  packSeed: number,
  contentVersion: string = CONTENT_VERSION,
): WeeklyConceptPack {
  const fixture = getFixture(level, week);
  if (fixture) return fixture;
  const builder = WEEK_BUILDERS.get(`${level}${week}`);
  if (!builder) {
    const available = AVAILABLE_WEEKS.map((w) => `${w.level}${w.week}`).join(', ');
    throw new Error(
      `No pack content for ${level} week ${week} (increment 2 covers: ${available})`,
    );
  }
  const pack = builder(packSeed, contentVersion);
  if (versionAtLeast(contentVersion, 1, 1)) applyRetrievalRamp(pack);
  // Pages are counted from the FINAL day contents — after the ramp, never inside a builder.
  restampPageCounts(pack);
  return pack;
}

function versionAtLeast(version: string, major: number, minor: number): boolean {
  const m = version.match(/^(\d+)\.(\d+)/);
  if (!m) return false;
  const [vMajor, vMinor] = [Number(m[1]), Number(m[2])];
  return vMajor > major || (vMajor === major && vMinor >= minor);
}

/**
 * LS1-R4 — retrieval ramp across the week (contentVersion ≥ 1.1.0, template
 * cells only; fixtures stay verbatim). The 1.0.0 authored day-mix is
 * front-loaded (Day 1 ≈33% retrieval, Days 4–5 25%); the research default
 * wants the retrieval share ramping ~20% → ~40% late-week instead. The
 * cheapest QG-legal move: relocate Day 1's LAST retrieval warm-up to Day 5
 * (re-minted into the D5 id slot). Result on the 2-retrieval Day-1 weeks:
 * D1 1/5 (20%) · D2–3 1/6 · D4 1/4 · D5 2/5 (40%). Pack-wide share is
 * unchanged, so the QG-2 20–30% gate still holds (QG gates win — a mix the
 * gates can't absorb is logged and skipped, per the addendum); per-day item
 * counts stay within the 3–8 structural bounds. Deterministic: no RNG draws.
 */
function applyRetrievalRamp(pack: WeeklyConceptPack): void {
  const day1 = pack.days.find((d) => d.day === 1);
  const day5 = pack.days.find((d) => d.day === 5);
  if (!day1 || !day5) return;
  const day1Retrieval = day1.items.filter((i) => i.isRetrieval);
  // Only ramp when Day 1 keeps ≥1 warm-up and Day 5 stays within QG-8 bounds.
  if (day1Retrieval.length < 2 || day5.items.length >= 8) return;
  const moved = day1Retrieval[day1Retrieval.length - 1];
  day1.items = day1.items.filter((i) => i !== moved);
  const { level, week } = pack.identity;
  day5.items = [
    ...day5.items,
    { ...moved, id: `${level}${week}-D5-${String(day5.items.length + 1).padStart(2, '0')}` },
  ];
}

/**
 * Convenience for session screens: the Day-N slice of a pack (1-based).
 * Day tiles / "today's content" read pack.days via this accessor.
 */
export function getPackDay(pack: WeeklyConceptPack, day: number): PackDay {
  const found = pack.days.find((d) => d.day === day);
  if (!found) throw new Error(`Pack ${pack.packId} has no day ${day}`);
  return found;
}

/**
 * The authored parent-facing summary for a cell, without a child or a seed.
 *
 * `parentSummarySeed` is authored prose in the week blueprint — no rng touches
 * it, so it is identical for every seed and every child doing that week. The
 * parent screens need it (the shared vocabulary especially) but have no pack in
 * hand: the parent context carries enrolments and reports, and packs are never
 * stored, by design. Building one throwaway pack per cell is the honest way to
 * read authored content back out, and the result is memoised because a parent
 * flipping through report history would otherwise rebuild the same week on
 * every render.
 *
 * Returns null for a cell with no content rather than throwing — a parent
 * screen must degrade to showing less, never to an error boundary.
 */
const parentSeedCache = new Map<string, ParentSummarySeed | null>();

export function getParentSummarySeed(level: BBLevel, week: number): ParentSummarySeed | null {
  const key = `${level}${week}`;
  const hit = parentSeedCache.get(key);
  if (hit !== undefined) return hit;
  let seed: ParentSummarySeed | null = null;
  try {
    // Any seed yields the same authored prose; 1 keeps it obvious that the
    // number is not meaningful here.
    seed = generatePack(level, week, 1).parentSummarySeed ?? null;
  } catch {
    seed = null;
  }
  parentSeedCache.set(key, seed);
  return seed;
}
