// ============================================
// Homework Helper & Exam Prep Types
// ============================================

// Mode and Status Enums
export type HomeworkMode = 'hw_helper' | 'exam_prep';

export type SessionStatus = 'pending' | 'processing' | 'ready' | 'completed' | 'error';

export type HomeworkProblemType =
  | 'addition'
  | 'subtraction'
  | 'multiplication'
  | 'division'
  | 'fractions'
  | 'decimals'
  | 'percentages'
  | 'algebra'
  | 'geometry'
  | 'word_problem'
  | 'order_of_operations'
  | 'other';

export type Difficulty = 'easy' | 'medium' | 'hard';

export type DifficultyPreference = 'easier' | 'balanced' | 'harder';

export type ErrorType =
  | 'calculation_error'
  | 'conceptual_error'
  | 'wrong_operation'
  | 'incomplete'
  | 'misread_problem'
  | 'other';

export type AIFeature =
  | 'extraction'
  | 'classification'
  | 'generation'
  | 'evaluation'
  | 'explanation'
  | 'chat'
  | 'audio';

// ============================================
// Problem Extraction Types
// ============================================

/**
 * A math problem extracted from an uploaded homework image
 */
export interface ExtractedProblem {
  /** Problem number if visible on the page */
  problem_number: string | null;
  /** The exact problem text */
  problem_text: string;
  /** Category of math problem */
  problem_type: HomeworkProblemType;
  /** Difficulty level */
  difficulty: Difficulty;
  /** Estimated grade level (K, 1, 2, ... 12) */
  grade_level: string;
  /** Confidence in extraction accuracy (0.0 to 1.0) */
  confidence: number;
  /** Student's handwritten answer if visible (null if blank) */
  student_answer?: string | null;
}

/**
 * Result of image quality assessment before extraction
 */
export interface ImageQualityAssessment {
  /** Is this math content? */
  is_math_content: boolean;
  /** Is the image clear enough to read? */
  is_readable: boolean;
  /** Estimated number of problems */
  estimated_problem_count: number;
  /** Quality score (0.0 to 1.0) */
  quality_score: number;
  /** List of issues found */
  issues: string[];
  /** Recommendation: proceed, retry, or not_math */
  recommendation: 'proceed' | 'retry' | 'not_math';
}

/**
 * Result of problem extraction from images
 */
export interface ExtractionResult {
  /** List of extracted problems */
  problems: ExtractedProblem[];
  /** Total problems found */
  total_found: number;
  /** Optional notes about extraction */
  notes?: string;
}

// ============================================
// Problem Classification Types
// ============================================

/**
 * Classification of a single problem
 */
export interface ProblemClassification {
  /** Index of the problem in the list */
  problem_index: number;
  /** Main concept being tested */
  primary_topic: string;
  /** Other concepts involved */
  secondary_topics: string[];
  /** Skills student needs to solve this */
  prerequisite_skills: string[];
}

/**
 * Result of classifying all problems in a session
 */
export interface ClassifiedProblems {
  /** Classifications for each problem */
  problem_classifications: ProblemClassification[];
  /** Summary of topics and their counts */
  topic_summary: Record<string, number>;
  /** AI-recommended focus areas */
  recommended_focus_areas: string[];
}

// ============================================
// Problem Generation Types
// ============================================

/**
 * A practice problem generated by AI
 */
export interface GeneratedProblem {
  /** Index in the practice test */
  index: number;
  /** The problem text */
  problem_text: string;
  /** Type of math problem */
  problem_type: HomeworkProblemType;
  /** Difficulty level */
  difficulty: Difficulty;
  /** Topic this problem covers */
  source_topic: string;
  /** The correct answer */
  answer: string;
  /** Steps to solve */
  solution_steps: string[];
}

// ============================================
// Answer Evaluation Types
// ============================================

/**
 * Result of evaluating a student's answer
 */
export interface EvaluationResult {
  /** Index of the problem */
  problem_index: number;
  /** Was the answer correct? */
  is_correct: boolean;
  /** What the student answered */
  student_answer: string;
  /** The correct answer */
  correct_answer: string;
  /** Type of error (if incorrect) */
  error_type?: ErrorType;
  /** Brief note about the error */
  brief_note?: string;
}

/**
 * Summary of batch evaluation
 */
export interface EvaluationSummary {
  /** Total problems evaluated */
  total: number;
  /** Number correct */
  correct: number;
  /** Number incorrect */
  incorrect: number;
}

/**
 * Full batch evaluation result
 */
export interface BatchEvaluationResult {
  /** Individual evaluations */
  evaluations: EvaluationResult[];
  /** Summary stats */
  summary: EvaluationSummary;
}

// ============================================
// Ms. Guide Explanation Types
// ============================================

/**
 * A single step in an explanation
 */
export interface ExplanationStep {
  /** Step number */
  step_number: number;
  /** What to do in this step */
  instruction: string;
  /** Visual representation (ASCII art, etc.) */
  visual?: string;
  /** Helpful tip for this step */
  tip?: string;
}

/**
 * Full Ms. Guide explanation for a wrong answer
 */
export interface MsGuideExplanation {
  /** Warm, encouraging opening */
  greeting: string;
  /** Acknowledge correct thinking (null if not applicable) */
  what_they_did_right: string | null;
  /** Gentle explanation of the mistake */
  the_mistake: string;
  /** Step-by-step solution */
  steps: ExplanationStep[];
  /** The correct answer */
  correct_answer: string;
  /** Closing encouragement */
  encouragement: string;
  /** Tag for the type of misconception */
  misconception_tag: string;
}

// ============================================
// Chat Types
// ============================================

export type ChatRole = 'student' | 'ms_guide';

/**
 * A message in the chat history
 */
export interface ChatMessage {
  /** Who sent the message */
  role: ChatRole;
  /** The message content */
  content: string;
  /** When the message was sent */
  timestamp: string;
}

/**
 * Context for a chat conversation
 */
export interface ProblemContext {
  /** The original problem text */
  problem_text: string;
  /** Student's original answer */
  student_answer: string;
  /** The correct answer */
  correct_answer: string;
  /** Student's grade level */
  grade_level: string;
  /** Previous explanation given */
  previous_explanation?: MsGuideExplanation;
  /** Kumon level (e.g., "A", "B", "C") - optional for Kumon practice */
  kumon_level?: string;
  /** Kumon skill set being practiced (e.g., "Addition Sums to 12") */
  kumon_skill_set?: string;
  /** Kumon worksheet number */
  kumon_worksheet?: number;
}

// ============================================
// Session & Test Types (Database Models)
// ============================================

/**
 * A homework or exam prep session
 */
export interface HomeworkSession {
  id: string;
  child_id: string;
  mode: HomeworkMode;
  image_count: number;
  extracted_problems: ExtractedProblem[];
  topics_identified: string[];
  status: SessionStatus;
  error_message?: string;
  created_at: string;
  updated_at: string;
}

/**
 * A practice test generated for exam prep
 */
export interface ExamPrepTest {
  id: string;
  session_id: string;
  generated_problems: GeneratedProblem[];
  problem_count: number;
  timer_enabled: boolean;
  time_limit_minutes?: number;
  difficulty_preference: DifficultyPreference;
  started_at?: string;
  completed_at?: string;
  score_percentage?: number;
  created_at: string;
}

/**
 * An attempt at a homework problem or test problem
 */
export interface HomeworkAttempt {
  id: string;
  session_id?: string;
  test_id?: string;
  problem_index: number;
  problem_text: string;
  problem_type?: HomeworkProblemType;
  difficulty?: Difficulty;
  grade_level?: string;
  correct_answer?: string;
  student_answer?: string;
  is_correct?: boolean;
  error_type?: ErrorType;
  time_spent_seconds?: number;
  needs_review: boolean;
  created_at: string;
}

/**
 * A review session with Ms. Guide
 */
export interface ReviewSession {
  id: string;
  attempt_id: string;
  explanation: MsGuideExplanation;
  chat_history: ChatMessage[];
  chat_message_count: number;
  audio_played: boolean;
  similar_problem_requested: boolean;
  similar_problem?: GeneratedProblem;
  created_at: string;
  updated_at: string;
}

/**
 * A homework image stored for processing
 */
export interface HomeworkImage {
  id: string;
  session_id: string;
  storage_path: string;
  file_name: string;
  file_size_bytes?: number;
  mime_type?: string;
  signed_url?: string;
  signed_url_expires_at?: string;
  uploaded_at: string;
  scheduled_deletion_at: string;
  deleted_at?: string;
}

/**
 * AI usage log entry
 */
export interface AIUsageLog {
  id: string;
  child_id: string;
  session_id?: string;
  feature: AIFeature;
  model: string;
  input_tokens?: number;
  output_tokens?: number;
  image_count: number;
  estimated_cost?: number;
  response_time_ms?: number;
  success: boolean;
  error_message?: string;
  created_at: string;
}

// ============================================
// UI State Types
// ============================================

/**
 * State for the image upload flow
 */
export interface ImageUploadState {
  /** Files selected for upload */
  files: File[];
  /** Preview URLs for selected files */
  previews: string[];
  /** Upload progress (0-100) */
  progress: number;
  /** Is upload in progress? */
  isUploading: boolean;
  /** Error message if upload failed */
  error?: string;
}

/**
 * State for the homework helper flow
 */
export interface HomeworkHelperState {
  /** Current step in the flow */
  step: 'upload' | 'extraction' | 'selection' | 'explanation' | 'complete';
  /** The active session */
  session?: HomeworkSession;
  /** Selected problem indices */
  selectedProblems: number[];
  /** Current problem being explained */
  currentProblemIndex: number;
  /** Active review session */
  activeReview?: ReviewSession;
  /** Is AI processing? */
  isProcessing: boolean;
  /** Error message */
  error?: string;
}

/**
 * State for the exam prep flow
 */
export interface ExamPrepState {
  /** Current step in the flow */
  step: 'upload' | 'extraction' | 'configuration' | 'test' | 'results' | 'review' | 'complete';
  /** The active session */
  session?: HomeworkSession;
  /** The active test */
  test?: ExamPrepTest;
  /** Student answers keyed by problem index */
  answers: Record<number, string>;
  /** Current problem index in test */
  currentProblemIndex: number;
  /** Problems flagged for review */
  flaggedProblems: number[];
  /** Evaluation results */
  results?: BatchEvaluationResult;
  /** Results by topic */
  resultsByTopic?: Record<string, { correct: number; total: number }>;
  /** Active review session (for wrong answers) */
  activeReview?: ReviewSession;
  /** Time remaining in seconds (if timer enabled) */
  timeRemaining?: number;
  /** Is AI processing? */
  isProcessing: boolean;
  /** Error message */
  error?: string;
}

/**
 * Test configuration for exam prep
 */
export interface TestConfiguration {
  /** Number of problems (5-25) */
  problemCount: number;
  /** Enable timer? */
  timerEnabled: boolean;
  /** Time limit in minutes (if timer enabled) */
  timeLimitMinutes?: number;
  /** Difficulty preference */
  difficultyPreference: DifficultyPreference;
  /** Include warm-up problems? */
  includeWarmups: boolean;
  /** Include challenge problems? */
  includeChallenges: boolean;
}

// ============================================
// Statistics Types
// ============================================

/**
 * Homework statistics for a child
 */
export interface HomeworkStats {
  /** Total sessions */
  total_sessions: number;
  /** Homework helper sessions */
  hw_helper_sessions: number;
  /** Exam prep sessions */
  exam_prep_sessions: number;
  /** Total problems helped with */
  total_problems_helped: number;
  /** Total practice tests taken */
  total_tests_taken: number;
  /** Average test score */
  average_test_score: number | null;
  /** Total review sessions */
  total_review_sessions: number;
}

// ============================================
// Service Configuration Types
// ============================================

/**
 * AI model configuration
 */
export interface AIModelConfig {
  /** Model for problem extraction */
  extraction: string;
  /** Model for problem generation */
  generation: string;
  /** Model for answer evaluation */
  evaluation: string;
  /** Model for explanations (student-facing) */
  explanation: string;
  /** Model for chat (student-facing) */
  chat: string;
}

/**
 * Limits configuration
 */
export interface HomeworkLimitsConfig {
  /** Max images for homework helper */
  maxImagesHwHelper: number;
  /** Max images for exam prep */
  maxImagesExamPrep: number;
  /** Max chat messages per session */
  maxChatMessages: number;
  /** Min practice problems */
  minPracticeProblems: number;
  /** Max practice problems */
  maxPracticeProblems: number;
  /** Default practice problems */
  defaultPracticeProblems: number;
  /** Max similar problems per session */
  maxSimilarProblems: number;
  /** Max image size in bytes */
  maxImageSizeBytes: number;
}

/**
 * Audio/TTS configuration
 */
export interface AudioConfig {
  /** Is audio enabled? */
  enabled: boolean;
  /** TTS provider */
  provider: 'google' | 'browser';
  /** Voice to use */
  voice: string;
  /** Speaking rate (0.5 to 2.0) */
  speakingRate: number;
}

// ============================================
// Cost Tracking Types
// ============================================

/**
 * Cost rates per model (per million tokens)
 */
export interface ModelCostRates {
  input: number;
  output: number;
}

/**
 * Cost estimate for a session
 */
export interface SessionCostEstimate {
  /** Cost for extraction */
  extraction: number;
  /** Cost for explanations */
  explanations: number;
  /** Cost for chat */
  chat: number;
  /** Cost for evaluation */
  evaluation: number;
  /** Cost for generation */
  generation: number;
  /** Cost for audio */
  audio: number;
  /** Total estimated cost */
  total: number;
}
