/**
 * Wire every authored week into `packGenerator.ts` (B2–B5 fan-out support).
 *
 * Adding one week means touching four places — the import, `WEEK_BUILDERS`,
 * `V2_WEEKS` and `GENERATED_WEEKS` — and the fill adds 88 of them. Hand-editing
 * that is how a week ends up generated but unlisted (or listed but not v2, so
 * the QG-11 detector silently stops blocking for it). So it is derived instead:
 * this script reads `templates/weeks/`, works out what is there, and rewrites
 * the four marked regions.
 *
 * A week is v2 iff its blueprint literally declares `pedagogyContract: 'v2'` —
 * read from the file, never assumed, so the contract flag and the gate can not
 * drift apart.
 *
 * Run: npx tsx scripts/bb-wire-weeks.ts        (add --check to only report)
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const WEEKS_DIR = path.join(ROOT, 'src/modules/best-brains/generator/templates/weeks');
const PACKGEN = path.join(ROOT, 'src/modules/best-brains/generator/packGenerator.ts');
const LEVELS = ['A', 'B', 'C', 'D', 'E'] as const;

interface Week {
  level: string;
  week: number;
  file: string;   // e.g. "e13"
  symbol: string; // e.g. "buildE13"
  v2: boolean;
}

const weeks: Week[] = [];
for (const f of fs.readdirSync(WEEKS_DIR).sort()) {
  const m = /^([a-e])(\d{2})\.ts$/.exec(f);
  if (!m) continue;
  const level = m[1].toUpperCase();
  const week = Number(m[2]);
  const src = fs.readFileSync(path.join(WEEKS_DIR, f), 'utf8');
  const sym = new RegExp(`export\\s+(?:const|function)\\s+(build${level}${m[2]})\\b`).exec(src);
  if (!sym) {
    console.error(`  SKIP ${f}: no exported build${level}${m[2]} symbol`);
    continue;
  }
  weeks.push({ level, week, file: `${m[1]}${m[2]}`, symbol: sym[1], v2: /pedagogyContract:\s*'v2'/.test(src) });
}

const order = (w: Week) => LEVELS.indexOf(w.level as (typeof LEVELS)[number]) * 100 + w.week;
weeks.sort((a, b) => order(a) - order(b));

const imports = weeks.map((w) => `import { ${w.symbol} } from './templates/weeks/${w.file}';`).join('\n');
const builders = weeks.map((w) => `  ['${w.level}${w.week}', ${w.symbol}],`).join('\n');
const v2 = weeks.filter((w) => w.v2).map((w) => `'${w.level}${w.week}'`);
const v2Block = v2.length
  ? v2.reduce<string[]>((lines, id, i) => {
      if (i % 12 === 0) lines.push('  ' + id + ',');
      else lines[lines.length - 1] += ' ' + id + ',';
      return lines;
    }, []).join('\n')
  : '';
/**
 * A cell backed by a PINNED FIXTURE must not be advertised as a template.
 *
 * `generatePack` resolves fixtures first, so where both exist the fixture wins
 * and the template is unreachable — yet listing it under GENERATED_WEEKS told
 * `bb-verify-packs` to assert seed SENSITIVITY on a cell that is deliberately
 * seed-independent, which is how B14 produced ten failures the moment its
 * mirror template landed. The builder stays imported and registered (so it is
 * type-checked, testable, and ready if the fixture is ever unpinned); it is only
 * the "servable template" claim that is withdrawn.
 */
const FIXTURE_BACKED = new Set(['A15', 'B14', 'D17']);
const generated = weeks
  .filter((w) => !FIXTURE_BACKED.has(`${w.level}${w.week}`))
  .map((w) => `  { level: '${w.level}', week: ${w.week} },`)
  .join('\n');

const REGIONS: Array<[string, string]> = [
  ['WEEK IMPORTS', imports],
  ['WEEK BUILDERS', builders],
  ['V2 WEEKS', v2Block],
  ['GENERATED WEEKS', generated],
];

let src = fs.readFileSync(PACKGEN, 'utf8');
let missing = false;
for (const [name, body] of REGIONS) {
  const begin = `// <<< ${name} (generated by scripts/bb-wire-weeks.ts) >>>`;
  const end = `// <<< END ${name} >>>`;
  const re = new RegExp(`${begin.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
  if (!re.test(src)) {
    console.error(`  MISSING REGION MARKERS for "${name}" in packGenerator.ts — add:\n    ${begin}\n    ${end}`);
    missing = true;
    continue;
  }
  src = src.replace(re, `${begin}\n${body}\n${end}`);
}
if (missing) process.exit(1);

const byLevel = LEVELS.map((L) => `${L}:${weeks.filter((w) => w.level === L).length}`).join(' ');
const shadowed = weeks.filter((w) => FIXTURE_BACKED.has(`${w.level}${w.week}`)).map((w) => `${w.level}${w.week}`);
console.log(`weeks found — ${byLevel}   (total ${weeks.length}; v2: ${v2.length})`);
if (shadowed.length) {
  console.log(`  fixture-shadowed (registered but the pinned fixture is served): ${shadowed.join(', ')}`);
}

if (process.argv.includes('--check')) {
  const same = fs.readFileSync(PACKGEN, 'utf8') === src;
  console.log(same ? 'packGenerator.ts is UP TO DATE' : 'packGenerator.ts is STALE — run without --check');
  process.exit(same ? 0 : 1);
}
fs.writeFileSync(PACKGEN, src);
console.log('packGenerator.ts rewritten.');
