/**
 * Level C · Week 12 — "Facts: ×8, ×9" (conceptId: facts-8-9).
 *
 * FILL-ARCHITECTURE §5 row C12: anchor "the 9s digit-sum pattern; ×8 = double
 * ×4"; multi-step "a fact then a compare"; error-analysis "9 × 7 = 62 (the
 * pattern slip)"; discrimination "the 8s pattern against the 9s pattern";
 * Day-5 signature "a pattern proof — why the 9s digits sum to 9 (R-lite)".
 *
 * The week's claim is that the two hardest-looking rows in the table are the two
 * that need the least remembering. Nine of something is TEN of it with one group
 * given back, and eight of something is a four-count doubled — so both rows are
 * reached from counts the child has owned since C7 and C8. And because 9n is
 * 10n − n, the answer is forced to look a particular way: the ten-count puts the
 * number of groups in the tens place, giving one group back drops that digit by
 * one and pays the difference into the ones, so the two digits are always one
 * below the number of groups and whatever is left of a whole ten — a pair that
 * cannot help adding to nine. The content is built so the child SEES that rather
 * than being told it:
 *  - the anchor item hands over the ten-group count as a drawn, finished block
 *    and asks for the nine-group count, so the block and the group being given
 *    back stand on the page as two separate things;
 *  - the cross-op discrimination is the size of that give-back, with its grid cut
 *    along the ninth row so the split is seen rather than described;
 *  - the structural discrimination puts the two rows against each other — one
 *    number, two counts, and only the patterns to decide it;
 *  - the metacognition probe is the route decision itself, made before any
 *    arithmetic: is this one a four-count doubled, or a ten-count minus a group;
 *  - three chains, one of them the give-back performed as a two-step story, one a
 *    fact then a compare, and one posed `has-distractor`;
 *  - Day 5 argues the pattern instead of reciting it: the proof is asked for as a
 *    proof (why the two digits have no choice), and the claim that closes the day
 *    is the converse — that every two-digit number whose digits make nine is in
 *    the count, which a child can settle by listing all nine of them.
 *
 * EVERY ×9 DRAW IS CAPPED AT TEN GROUPS. The digit-sum claim is true of 9 × 1
 * through 9 × 10 and false at 9 × 11 (99 → 18), so no generator in this week may
 * draw a nines multiplier above ten. That cap is a content law here, not a
 * convenience: a week whose own anchor breaks on an item it generated would be
 * teaching a rule and then quietly disproving it.
 *
 * POSING (PEDAGOGY-CEILING-REVIEW F3). C7 and C8 spent `goal-first` and C11
 * spent `inverse-start`, so this week spends `has-distractor` — in a shape no
 * earlier C week has used. C6's and C8's unused quantities were foreign to the
 * count (a price among people); the plum stall's unused number is the WEEK'S OWN
 * FACTOR sitting in the story as a time of day. A child who has spent four days
 * multiplying by eight and nine has been trained by the page itself to reach for
 * exactly that numeral, which is the strongest form the trap can take.
 *
 * THE ERROR-ANALYSIS, and why it uses a verify template from another family
 * (kit §E2.3, declared here rather than buried). The recipe names "9 × 7 = 62",
 * and 62 is not a fabrication — it is what the pattern produces when its two
 * digit-sequences are read out of step. The tens digit climbs (n − 1) while the
 * ones digit falls (10 − n); a child who walks the falling one a single step too
 * far writes 9 − n where 10 − n belonged, giving
 *   10(n − 1) + (9 − n) = 10n − 10 + 9 − n = 9n − 1,
 * i.e. the truth, exactly one short. So the misconception's output IS `truth − 1`
 * for every n, provably.
 *
 * No operation-swap reaches it. `d_verify_binop_misconception_v1` varies the OP
 * over ONE fixed operand pair, and solving `a op b = 9n` with `a op' b = 9n − 1`
 * over {+, −, ×, ÷} leaves only the degenerate pair (9n, 1) under ÷ against −,
 * whose operands have nothing to do with the story. `e_alg_verify_distribute_v1`
 * (C11's) needs b(a − 1) = 1, so a = 2 — a multiplier with no business in a
 * nines item. The recipe's own item is the better one (kit §E2.3, first bullet),
 * so it is generated by the one registered transform that computes exactly
 * "the truth, one short": `a_verify_count_slip_v1` with `slip: 'skip-count'`,
 * which returns `{correct: n, wrong: n − 1}`. Both numbers are code-derived from
 * one param; the template's transform and this week's misconception coincide
 * identically, which is the same coincidence C4 found for the borrow-across-zero
 * slip. The item's prose says what the student did and shows their working; the
 * diagnosis — that the two digits no longer make nine — stays the child's answer.
 *
 * FIGURE LAW as applied here (kit §F.7, §E2.5). Two day items carry a picture:
 *  - the anchor's bar draws the TEN carriages the prose has already counted and
 *    asserts that block against the item's own drawn param. The carriage being
 *    roped off is the child's move and is not marked;
 *  - the give-back discrimination's grid draws the ten-row block with nine rows
 *    shaded — legitimate there and nowhere else, because that item's answer is a
 *    CHOICE of calculation rather than a count, so the picture cannot hand over
 *    what is being asked. It is what makes the give-back visible.
 * The pictures that show a give-back finished — the ten-count beside the
 * nine-count, the four-count doubled, and the near-miss that lands one short —
 * live where the answer is already on the page: the lesson script and the
 * guided examples.
 *
 * Retrieval is backward-only into C3/C4 (± within 1,000), into C7 (the ×10 fact,
 * which is the count every nines rebuild starts from), into C8 (the ×4 fact,
 * which is the count every eights rebuild starts from) and into C10 (the fact
 * family read as a division).
 */

import { asWarmup, addWhole, classify, divideExact, reasoning, subWhole } from '../lib/items';
import type { ItemGen } from '../lib/items';
import { situation } from '../lib/situations';
import { multiStep } from '../lib/multistep';
import { discrimination } from '../lib/discrimination';
import type { DiscriminationDraw } from '../lib/discrimination';
import { errorAnalysis } from '../lib/erroranalysis';
import { withEstimateFirst } from '../lib/metacog';
import { countNoun } from '../lib/format';
import { makeGe, makeWeekBuilder } from '../lib/assemble';
import { areaGrid, assertsAnswerOf, assertsParam, barModel } from '../lib/figures';
import type { BBFigure } from '../../../figures/types';
import type { Rng } from '../../rng';

const ge = makeGe('C');

const C3 = { level: 'C' as const, week: 3 };
const C4 = { level: 'C' as const, week: 4 };
const C6 = { level: 'C' as const, week: 6 };
const C7 = { level: 'C' as const, week: 7 };
const C8 = { level: 'C' as const, week: 8 };
const C10 = { level: 'C' as const, week: 10 };
const C11 = { level: 'C' as const, week: 11 };

const NAMES = ['Maya', 'Leo', 'Ava', 'Ben', 'Mia', 'Sam', 'Ria', 'Noor', 'Ken', 'Pia', 'Tom', 'Zoe'] as const;
/** One drawn name. Never hardcode a name that is also in this pool (kit §A.3). */
const one = (r: Rng): string => r.pick(NAMES);

/**
 * The two facts this week owns. Every core item is an eights or a nines story,
 * so the shortest honest route is always a count the child already has: a
 * four-count doubled, or a ten-count with one group handed back.
 */
const THIS_WEEK = [8, 9] as const;

/** The nines cap (see the header): 9 × 11 = 99, whose digits make eighteen. */
const NINES_MAX = 10;

// ---------------------------------------------------------------------------
// withFigure — attach a picture built from the item's OWN generator params.
//
// The shipped primitives (situation / multiStep) have no figure slot, and lib/
// is not ours to edit, so this wrapper does what `withEstimateFirst` does: it
// works entirely inside the returned closure, takes no new rng draw, and leaves
// the prompt (and therefore the QG-1/QG-4 surface signature) untouched. It reads
// the drafted item's `generator.params` — the very numbers the answer was
// computed from — so the figure law ("built from the item's own drawn values")
// holds by construction. (Pattern established by c06, the Level-C exemplar.)
// ---------------------------------------------------------------------------

type Params = Record<string, unknown>;
const numOf = (p: Params, k: string): number => Number(p[k]);

function withFigure(base: ItemGen, build: (params: Params) => BBFigure): ItemGen {
  return (rng, guard, difficulty) => {
    const d = base(rng, guard, difficulty);
    return d.generator ? { ...d, figure: build(d.generator.params) } : d;
  };
}

// ---------------------------------------------------------------------------
// discriminationFig — the same idea for a discrimination item.
//
// `discrimination()` ships no GeneratorSpec (its truth is the code-SELECTED
// correct option, not a recomputed product), so there are no `generator.params`
// for `withFigure` to read and no `asserts` clause QG-13 could check against.
// The figure is therefore built by the item's OWN draw closure, from the very
// numbers the prompt and the options were written from, and handed out beside
// the draft.
//
// Determinism (kit §E2.4): `drawUniqueItem` may build several drafts and returns
// the LAST one it built, and generation is synchronous, so `pending` always
// holds the figure belonging to the draft that is actually returned. No new rng
// draw is taken, and the state is per-generator rather than module-wide.
// ---------------------------------------------------------------------------

function discriminationFig(cfg: {
  variant: 'cross-op' | 'structural';
  cognitiveOp?: string;
  draw: (r: Rng) => DiscriminationDraw & { figure: BBFigure };
}): ItemGen {
  let pending: BBFigure | undefined;
  const base = discrimination({
    variant: cfg.variant,
    ...(cfg.cognitiveOp ? { cognitiveOp: cfg.cognitiveOp } : {}),
    draw: (r) => {
      const { figure, ...rest } = cfg.draw(r);
      pending = figure;
      return rest;
    },
  });
  return (rng, guard, difficulty) => {
    const d = base(rng, guard, difficulty);
    return pending ? { ...d, figure: pending } : d;
  };
}

// ---------------------------------------------------------------------------
// Retrieval warm-ups (strictly earlier weeks; exempt from the pedagogy gates)
// ---------------------------------------------------------------------------

/** C3 — addition within 1,000: the recombine a compare finishes on. */
const wAdd = asWarmup(addWhole(146, 495), C3);
/** C4 — subtraction within 1,000, the operation every give-back is made of. */
const wSub = asWarmup(subWhole(168, 879), C4);
/**
 * C10 — a fact family read backwards, kept warm as bare arithmetic. The divisor
 * stays inside the threes, fours and fives ON PURPOSE: a warm-up divisor of
 * eight or nine would be asking the child to use, cold, the very facts this week
 * is teaching them how to build.
 */
const wDivFacts = asWarmup(divideExact(3, 5, 3, 9), C10);

/**
 * C7 — the ×10 fact, in the plainest form there is. This is not decoration: the
 * ten-count is the launch pad every nines rebuild jumps from, so Monday works by
 * hand the thing Tuesday starts leaning on.
 */
const wTenFact = asWarmup(
  situation({
    situationType: 'combine',
    cognitiveOp: 'mul',
    draw: (r) => {
      const strings = r.int(3, 9);
      const name = one(r);
      return {
        prompt: `${name} hangs ${countNoun(strings, 'strings')} of bunting along the school fence, and every string carries ${countNoun(10, 'flags')}. How many flags are flying?`,
        answerValue: String(10 * strings),
        templateId: 'd_mul_v1',
        params: { a: 10, b: strings },
        units: 'flags',
        hints: [
          'What does a single string of this bunting carry?',
          'Say the tens count aloud, one number for each string on the fence, and stop on the last one.',
        ],
        errorTags: ['fact-recall', 'representation-misread'],
      };
    },
  }),
  C7,
);

/**
 * C8 — the ×4 fact, the other launch pad. An eights fact is this count doubled,
 * so the week's second route is only as safe as this one is quick.
 */
const wFourFact = asWarmup(
  situation({
    situationType: 'rate',
    cognitiveOp: 'mul',
    draw: (r) => {
      const teams = r.int(3, 9);
      return {
        prompt: `Every relay team has ${countNoun(4, 'runners')} in it. ${countNoun(teams, 'teams')} line up for the last race of the day. How many runners are on the track?`,
        answerValue: String(4 * teams),
        templateId: 'd_mul_v1',
        params: { a: 4, b: teams },
        units: 'runners',
        hints: [
          'Do all the teams in this race carry the same number of runners?',
          'Take what a single team puts on the track, and take it again once for every team at the start.',
        ],
        errorTags: ['fact-recall', 'procedure-slip'],
      };
    },
  }),
  C8,
);

// ---------------------------------------------------------------------------
// Single-step facts — the two routes seen from four different situations
// ---------------------------------------------------------------------------

/**
 * THE ANCHOR ITEM. The ten-carriage count is already made and DRAWN, and the bar
 * is exactly that block, asserted against the count the prose states. The child
 * gives one carriage back. So the two parts stand on the page as two separate
 * things — one finished in front of them, one still to take away — which is the
 * whole of "ten groups with one group given back".
 *
 * The picture cannot leak: it draws the block the story already handed over, and
 * the answer is that block with one group gone.
 */
const sitParkTrain = withFigure(
  situation({
    situationType: 'part-whole',
    cognitiveOp: 'mul',
    usesPriorSkill: true,
    draw: (r) => {
      // Three to nine a carriage: the ten-count then stays inside two digits,
      // which is where the digit pattern the week teaches can be read at all.
      const per = r.int(3, 9);
      const name = one(r);
      return {
        prompt: `[image: the ten carriages the park train pulls] The park train pulls ${countNoun(10, 'carriages')} and every carriage seats ${countNoun(per, 'children')}, which is ${countNoun(10 * per, 'seats')} in all. This morning ${name} finds one carriage roped off while its door is mended. How many children can ride?`,
        answerValue: String(9 * per),
        templateId: 'd_mul_v1',
        params: { a: 9, b: per, ten: 10 * per },
        units: 'children',
        hints: [
          'Does the number the story hands you belong to the whole train, or to one carriage more than the question asks about?',
          'Take the full count the story states and let one whole carriage-load go from it.',
        ],
        errorTags: ['task-comprehension', 'concept-misconception'],
      };
    },
  }),
  (p) => {
    const per = numOf(p, 'b');
    const ten = numOf(p, 'ten');
    return barModel(
      [
        {
          label: 'the ten carriages',
          segments: Array.from({ length: 10 }, () => ({ value: per, label: String(per) })),
          total: String(ten),
        },
      ],
      {
        alt: `one bar cut into ten equal parts, ${countNoun(per, 'seats')} in each — ${countNoun(ten, 'seats')} on the whole train`,
        asserts: assertsParam('ten'),
      },
    );
  },
);

/**
 * The nines carried by a real nine, so the numeral is never arbitrary: a skittle
 * frame stands nine pins, which is why the game was once called ninepins. Here
 * it is the number of LANES that is drawn, so the nine sits on the group-size
 * side of the fact.
 */
const sitSkittleFrames = situation({
  situationType: 'combine',
  cognitiveOp: 'mul',
  usesPriorSkill: true,
  draw: (r) => {
    const lanes = r.int(3, NINES_MAX);
    return {
      prompt: `A skittle alley stands ${countNoun(9, 'skittles')} at the end of every lane. ${countNoun(lanes, 'lanes')} are set up for club night. How many skittles are standing?`,
      answerValue: String(9 * lanes),
      templateId: 'd_mul_v1',
      params: { a: 9, b: lanes },
      units: 'skittles',
      hints: [
        'Is there a friendlier count sitting one group above the one being asked for?',
        'Reach the ten-count in your head, then give one group back and stop there.',
      ],
      errorTags: ['fact-recall', 'concept-misconception'],
    };
  },
});

/**
 * The eights carried by an object that performs the doubling itself: a pizza cut
 * in four and then every quarter cut again is eight slices, so "×8 is a
 * four-count doubled" is the knife rather than a rule.
 */
const sitPizzaSlices = situation({
  situationType: 'rate',
  cognitiveOp: 'mul',
  usesPriorSkill: true,
  draw: (r) => {
    const pizzas = r.int(3, 12);
    const name = one(r);
    return {
      prompt: `Every pizza at the party is cut into quarters and each quarter is cut again, which makes ${countNoun(8, 'slices')}. ${name} carries ${countNoun(pizzas, 'pizzas')} out to the long table. How many slices is that?`,
      answerValue: String(8 * pizzas),
      templateId: 'd_mul_v1',
      params: { a: 8, b: pizzas },
      units: 'slices',
      hints: [
        'Which fact do you already own that is exactly half of the one wanted here?',
        'Settle half of it first, then lay that same amount down a second time.',
      ],
      errorTags: ['fact-recall', 'procedure-slip'],
    };
  },
});

/**
 * Metacognition base — served ONLY through the estimate-first wrapper, never
 * raw, so its ladder is counted once (kit §E2.2).
 *
 * The probe is the week's own decision and it is a genuine call, because the
 * number of sacks is drawn from the two facts: eight is a four-count doubled and
 * nine is a ten-count with a group handed back, and which of those a story wants
 * has to be read off the page before a single multiplication happens.
 *
 * THE SACK WEIGHT NEVER LANDS ON EIGHT, NINE OR TEN (kit §E2.7 — a computable
 * answer is not the same as an askable question). Multiplication commutes, so a
 * load of eight sacks weighing nine each is honestly BOTH facts: the child could
 * double a four-count or hand a group back from a ten-count and be right either
 * way, and the probe would be asking a question with two defensible answers. Held
 * between three and seven, exactly one of the two routes reaches the load.
 */
const sitFeedSacks = situation({
  situationType: 'measurement',
  cognitiveOp: 'mul',
  usesPriorSkill: true,
  draw: (r) => {
    const each = r.int(3, 7);
    const sacks = r.pick(THIS_WEEK);
    return {
      prompt: `A sack of pony feed weighs ${countNoun(each, 'kg')}. The trailer is loaded with ${countNoun(sacks, 'sacks')} of it. How heavy is the load?`,
      answerValue: String(each * sacks),
      templateId: 'd_mul_v1',
      params: { a: each, b: sacks },
      units: 'kg',
      hints: [
        'Which nearby count would you rather start from here — one you reach by doubling, or one you reach in tens?',
        'Follow the route you named right to the end, then set what you land on beside the ten-count and see whether it sits where it should.',
      ],
      errorTags: ['task-comprehension', 'fact-recall'],
    };
  },
});
const sitFeedSacksEstimate = withEstimateFirst(
  sitFeedSacks,
  'does this load come from a four-count doubled, or from a ten-count with one group handed back?',
);

// ---------------------------------------------------------------------------
// Multi-step: the C12 recipe's "a fact then a compare", in three postures
// ---------------------------------------------------------------------------

/**
 * The give-back performed as a story rather than described as a rule: the run is
 * ten hours long and one hour of it is lost, so the chain IS 10n − n and its
 * answer is the nines fact. The plainest two-step this week can write, and the
 * one that makes the anchor a thing the child DOES.
 */
const msPosterRun = multiStep({
  situationType: 'rate-of-change',
  usesPriorSkill: true,
  draw: (r) => {
    const perHour = r.int(3, NINES_MAX);
    return {
      prompt: `A screen printer presses ${countNoun(perHour, 'posters')} an hour and keeps going for ${countNoun(10, 'hours')}. The posters from the first hour dry crooked and go into the recycling. How many posters are left to sell?`,
      initN: perHour,
      steps: [
        { op: 'mul' as const, n: 10, d: 1 },
        { op: 'sub' as const, n: perHour, d: 1 },
      ],
      units: 'posters',
      hints: [
        'Does the whole run go on sale, or only part of it?',
        'Total up everything the machine turned out before you take anything away from it.',
      ],
      errorTags: ['task-comprehension', 'procedure-slip'],
    };
  },
});

/**
 * THE RECIPE'S ROW: a fact, then a compare. One haul has to be built up from an
 * eights fact and the other is simply stated, so the comparison cannot begin
 * until the multiplication has finished — which is exactly the ordering children
 * lose when a story hands them two numbers and the word "more".
 */
const msSwimGala = multiStep({
  situationType: 'multi-stage',
  usesPriorSkill: true,
  draw: (r) => {
    const perEvent = r.int(3, 9);
    // A rival haul equal to one event's medals reads as a coincidence rather
    // than a second club, and it blurs the boundary between the two steps this
    // item exists to draw. One deterministic step, never a redraw loop (kit
    // §E2.4); the nudged value stays well below the smallest eight-event haul.
    let rival = r.int(5, 20);
    if (rival === perEvent) rival += 3;
    return {
      prompt: `A swimming club won ${countNoun(perEvent, 'medals')} at each of ${countNoun(8, 'events')} this season. The club across the town won ${countNoun(rival, 'medals')} altogether. How many more medals did the swimming club win?`,
      initN: perEvent,
      steps: [
        { op: 'mul' as const, n: 8, d: 1 },
        { op: 'sub' as const, n: rival, d: 1 },
      ],
      units: 'medals',
      hints: [
        'Which club\'s medals does this story make you work out, and which club\'s does it simply tell you?',
        'Build one club\'s season up event by event first, and only then set the two hauls side by side.',
      ],
      errorTags: ['task-comprehension', 'representation-misread'],
    };
  },
});

/**
 * HAS-DISTRACTOR (PEDAGOGY-CEILING-REVIEW F3 — the posture C7, C8 and C11 did
 * not spend in this shape). The unused quantity is not foreign to the story and
 * it is not a price: it is the numeral NINE, sitting in the sentence as a time of
 * day, in the week whose whole business is multiplying by nine. Four days of
 * eights and nines train the eye to grab it, which is the strongest form this
 * trap can take and the reason it belongs here rather than anywhere else.
 */
const msPlumBoxes = multiStep({
  situationType: 'combine',
  usesPriorSkill: true,
  posing: 'has-distractor',
  draw: (r) => {
    const boxes = r.int(3, 9);
    // Fewer loose plums than a box holds, or the bowl is really another box and
    // the two steps stop being two different ideas.
    const loose = r.int(2, 7);
    return {
      prompt: `A grower packs ${countNoun(8, 'plums')} into every box. The market stall opens at 9 o'clock with ${countNoun(boxes, 'boxes')} on the table and ${countNoun(loose, 'loose plums')} in a bowl beside them. How many plums has the stall got altogether?`,
      initN: 8,
      steps: [
        { op: 'mul' as const, n: boxes, d: 1 },
        { op: 'add' as const, n: loose, d: 1 },
      ],
      units: 'plums',
      hints: [
        'Which of these numbers has nothing to do with how much fruit is on the stall?',
        'Deal with the packed fruit first, bring the bowl in after that, and let the number that tells the time stay where it is.',
      ],
      errorTags: ['task-comprehension', 'representation-misread'],
    };
  },
});

// ---------------------------------------------------------------------------
// Discrimination — the week's point, forced as a CHOICE
// ---------------------------------------------------------------------------

/**
 * The size of the give-back, as a choice of calculation. Its two distractors are
 * the week's two live confusions side by side — one of the things handed back
 * where a whole group belonged, and the number of GROUPS handed back rather than
 * what one group holds.
 *
 * This is the ONE item where the whole ten-group block may be drawn: its answer
 * is a choice of calculation rather than a count, so the picture cannot hand over
 * what is being asked, and shading nine of the ten rows is what makes the
 * give-back visible instead of merely described.
 */
const discrimGiveOneBack = discriminationFig({
  variant: 'cross-op',
  cognitiveOp: 'choose-operation',
  draw: (r) => {
    // Three to nine a jar: at one the "one back" option and the "one group back"
    // option print the same calculation, and at ten the "ten back" option does.
    const per = r.int(3, 9);
    const ten = 10 * per;
    const name = one(r);
    return {
      prompt: `${name} has already counted ${countNoun(10, 'jars')} of conkers: ${countNoun(ten, 'conkers')} in all. Only nine of the jars will fit in the display case. Which calculation gives the number of conkers in the case?`,
      correct: `${ten} − ${per}`,
      distractors: [
        {
          text: `${ten} − 1`,
          errorTag: 'concept-misconception',
          rationale: 'Hands back a single conker where a whole jar went back, so a count of ten jars barely moves.',
        },
        {
          text: `${ten} − 10`,
          errorTag: 'representation-misread',
          rationale: 'Hands back ten because ten jars were counted, rather than the amount one jar actually holds.',
        },
      ],
      hints: [
        'Is one whole jar coming off this count, or a single conker out of it?',
        'Find what one jar holds, and let exactly that much go from the count the story has already made.',
      ],
      errorTags: ['concept-misconception', 'representation-misread'],
      figure: areaGrid(
        { rows: 10, cols: per, shadedRows: 9 },
        {
          alt: `ten rows of ${countNoun(per, 'conkers')}, with nine of the rows shaded and the tenth row left plain`,
        },
      ),
    };
  },
});

/**
 * THE RECIPE'S DISCRIMINATION: the 8s pattern against the 9s pattern. One number,
 * two counts, and nothing to settle it but what each count does to the numbers it
 * lands on. Its distractors are the two live slips — the row next door, whose
 * step is one smaller, and a ten-count with a single one taken off it, which
 * lands beside the answer and looks like it.
 *
 * The drawn multiplier stays between four and eight so that neither the eights
 * nor the nines opening printed in the prompt is itself an option, and so that
 * only the true answer is a multiple of nine (at nine groups the eights answer
 * would be seventy-two, which is in both counts and would give the item two
 * right answers).
 */
const discrimWhichRow = discrimination({
  variant: 'structural',
  cognitiveOp: 'pattern-membership',
  draw: (r) => {
    const k = r.int(4, 8);
    const name = one(r);
    return {
      prompt: `Two counts are pinned above ${name}'s desk. One opens 8, 16, 24 and climbs in eights; the other opens 9, 18, 27 and climbs in nines. Which of these numbers turns up on the NINES count?`,
      correct: String(9 * k),
      distractors: [
        {
          text: String(8 * k),
          errorTag: 'representation-misread',
          rationale: 'Belongs to the count pinned beside it — the eights, whose step is one smaller at every rung.',
        },
        {
          text: String(10 * k - 1),
          errorTag: 'concept-misconception',
          rationale: 'A ten-count with a single one taken off it, which lands close to a nines answer without ever being one.',
        },
      ],
      hints: [
        'What happens to the two digits of a number as a count in nines climbs?',
        'Test each number against both counts: run up the eights, then run up the nines, and see which list says it.',
      ],
      errorTags: ['representation-misread', 'concept-misconception'],
    };
  },
});

// ---------------------------------------------------------------------------
// Day-5 error-analysis (generated; QG-11 re-derives both numbers)
//
// See the header note. `a_verify_count_slip_v1` computes the truth as the nines
// product and the shown wrong value as that truth one short — which is exactly
// what the pattern produces when the falling ones digit is walked a step too far
// (10(n−1) + (9−n) = 9n − 1). The student's tens digit is right and their
// arithmetic is faultless, so re-checking the working finds nothing; the only way
// in is the week's own check on the two digits.
// ---------------------------------------------------------------------------

const eaPatternSlip = errorAnalysis({
  verifyTemplateId: 'a_verify_count_slip_v1',
  cognitiveOp: 'error-analysis',
  drawParams: (r) => {
    const groups = r.int(3, 9);
    return { n: 9 * groups, slip: 'skip-count', groups };
  },
  build: (v, p) => {
    const groups = numOf(p, 'groups');
    return {
      prompt: `A class is filling in the nines row of a fact chart. One student says they never work a nines fact out at all: the tens digit climbs a step at every fact, and the ones digit falls a step. Asked for ${countNoun(groups, 'nines')}, they wrote 9 × ${groups} = ${v.wrong}.`,
      extension: 'Work out what that many nines really comes to, then write one sentence saying what the two digits of the student\'s number add up to and what that tells you.',
      hints: [
        'What do the two digits of a nines answer come to, every single time?',
        'Take the ten-count of that many, hand one whole group back, and read the two digits of what you land on.',
      ],
      errorTags: ['procedure-slip', 'representation-misread'],
    };
  },
});

// ---------------------------------------------------------------------------
// The week
// ---------------------------------------------------------------------------

export const buildC12 = makeWeekBuilder({
  level: 'C',
  week: 12,
  conceptId: 'facts-8-9',
  conceptName: 'Facts: ×8, ×9',
  strandTags: ['multiplication-division'],
  prerequisiteWeeks: [C6, C7, C8, C11],
  pedagogyContract: 'v2',
  conceptualAnchor: 'ten groups with one group given back',
  conceptFamily: 'operation',
  deepeningDelta:
    'C7 made the easiest facts quick by naming a count the child already had, C8 built the fours by doubling a doubling, and C11 reached the sixes and sevens by stepping ONTO a known fact — five groups and one more group. C12 turns that step round. The nines are reached by overshooting deliberately and coming back: ten groups, then one group given back, which is the first time this level asks a child to pass the answer on purpose. And because that route is a subtraction from a ten-count, it does something none of the earlier rebuilds did — it forces the shape of the answer, so this is also the first week whose facts can be CHECKED without being worked out again.',
  explanation: {
    hook:
      'The two rows children dread are the two that need the least remembering. Nine of something is ten of it with one group handed back — and ten of anything you have never had to think about.',
    whyBeforeHow:
      'Nine groups are ten groups with one group given back, and because a ten-count is the easiest count there is, every nines fact is a fact you can reach by overshooting on purpose and stepping back once. That is why this week never asks you to memorise a nines row. Watch what the give-back does to the answer, though, because it is the same every time: ten of them puts the number of groups in the tens place with a zero behind it, and handing one group back breaks one of those tens open — so the tens digit drops to one below the number of groups, and the broken ten pays back whatever is left of it into the ones. One digit one below the number of groups, the other digit whatever is left of a whole ten: those two always fill a nine between them. The eights need no giving back at all. Eight of something is a four-count doubled, and since four is itself a double, an eights fact is a doubling done to a doubling — no row to recite, just the same move twice more.',
    script: [
      {
        say: 'Watch what I do when a nines fact will not come. I want nine sevens, and nine sevens I am not sure of. But ten sevens I have never had to think about, because a ten-count only ever writes the number of groups in front of a zero: 10 × 7 = 70. Nine groups is ten groups with one group given back, so I take one seven off seventy and land on sixty-three. I did not remember nine sevens. I overshot and stepped back.',
        visual: 'A bar of ten sevens, and beneath it the same bar with one seven handed back.',
        figure: barModel(
          [
            { label: 'ten sevens', segments: Array.from({ length: 10 }, () => ({ value: 7 })), total: '70' },
            {
              label: 'nine sevens',
              segments: [...Array.from({ length: 9 }, () => ({ value: 7 })), { value: 7, fill: 'hatch' as const }],
              total: '63',
            },
          ],
          { scaleMax: 70, alt: 'a bar of seventy made of ten sevens, and beneath it the same bar with its last seven hatched as the group handed back' },
        ),
      },
      {
        say: 'Now look at what that give-back does to the two digits, because it is worth more than the answer. Seventy has a seven in the tens and nothing in the ones. Handing one seven back breaks one of those tens open, so the tens digit drops to six — always one below the number of groups — and the broken ten pays back what is left of it, which is three. Six and three. One digit sits one below the number of groups and the other is whatever is left of a whole ten, so the two of them are forced to make nine, in every single nines fact there is.',
        visual: 'Ten rows of seven with nine rows shaded, the tenth row left plain as the group given back.',
        figure: areaGrid(
          { rows: 10, cols: 7, shadedRows: 9 },
          { alt: 'ten rows of seven, with nine of the rows shaded and the tenth row left plain as the group handed back' },
        ),
      },
      {
        say: 'The eights ask for no give-back at all. Four sevens is twenty-eight, and eight sevens is that same amount twice over: 28 + 28 = 56. I never touched a nine and I never recited an eights row — I doubled a fact I was sure of, and four is itself a double, so an eights fact is really one move done twice more.',
        visual: 'A bar of four sevens above a bar of eight sevens, twice its length.',
        figure: barModel(
          [
            { label: 'four sevens', segments: Array.from({ length: 4 }, () => ({ value: 7 })), total: '28' },
            { label: 'eight sevens', segments: Array.from({ length: 8 }, () => ({ value: 7 })), total: '56' },
          ],
          { scaleMax: 56, alt: 'a bar of twenty-eight made of four sevens above a bar of fifty-six made of eight sevens' },
        ),
      },
      {
        say: 'One habit before any answer goes down: I check it rather than trust it. A nines answer has to land just below the ten-count, near it and not miles off, and its two digits have to come to nine. An eights answer has to be even, because doubling cannot finish anywhere else. Those checks cost a second each, and the answer they catch is nearly always the one that is a single step out — sixty-two where sixty-three belonged.',
        visual: 'A bar for the answer whose digits make nine beside a barely shorter bar for the answer one below it.',
        figure: barModel(
          [
            { label: 'the answer whose digits make nine', segments: [{ value: 63 }], total: '63' },
            { label: 'the answer one step below it', segments: [{ value: 62, fill: 'hatch' as const }], total: '62' },
          ],
          { scaleMax: 70, alt: 'a bar of sixty-three beside a barely shorter bar of sixty-two' },
        ),
      },
    ],
    summary:
      'Overshoot and step back: ten groups, then one group given back, and the nines are yours without a row to recite. Double a doubling and the eights are yours too. Then check what you wrote before you leave it — a nines answer sits just under the ten-count and its two digits make nine, and an eights answer is always even.',
    vocabulary: [
      { term: 'ten-count', kidGloss: 'ten of something — the easiest count there is, because it writes the number of groups in front of a zero' },
      { term: 'give a group back', kidGloss: 'go one group too far on purpose, then take one whole group off again' },
      { term: 'digit check', kidGloss: 'adding the two digits of an answer to see whether it can belong to the nines' },
      { term: 'eight times as many (×8)', kidGloss: 'a four-count doubled' },
    ],
  },
  guidedExamples: [
    {
      ...ge(12, 1, 'modeled', 'A gardener sets out 9 window boxes and plants 7 crocuses in every box. How many crocuses is that?', [
        {
          teacherSay:
            'Watch me refuse to hunt for nine sevens. Ten window boxes I could do in my sleep — that is seventy — and nine boxes is one box short of ten. So I put seventy on the table and look at what has to leave it: one whole box of seven, not one crocus.',
        },
        {
          teacherSay: 'Seventy, with one box of seven handed back — where does that land?',
          expected: '63',
        },
      ], '63'),
      visual: 'The ten-box count, and beneath it the nine-box count it is cut down to.',
      figure: barModel(
        [
          { label: 'ten boxes of seven', segments: Array.from({ length: 10 }, () => ({ value: 7 })), total: '70' },
          { label: 'nine boxes of seven', segments: Array.from({ length: 9 }, () => ({ value: 7 })), total: '63' },
        ],
        {
          scaleMax: 70,
          alt: 'a bar of seventy for ten boxes of seven above a bar of sixty-three for nine boxes of seven',
          asserts: assertsAnswerOf('bar:1'),
        },
      ),
    },
    {
      ...ge(12, 2, 'completion', 'A cafe cuts every pizza into 8 slices and puts 7 pizzas out on the counter. How many slices are on the counter?', [
        { teacherSay: 'Which easy fact sits exactly halfway to eight sevens?', expected: 'four sevens' },
        { childDo: 'Count the slices there would be if every pizza were still in quarters, double that, and say how many slices are on the counter.', expected: '56' },
      ], '56'),
      visual: 'Eight rows of seven slices, with the bottom four shaded as the fact already known.',
      figure: areaGrid(
        { rows: 8, cols: 7, shadedRows: 4 },
        {
          alt: 'eight rows of seven slices, with the bottom four rows shaded as the four-count already known',
          asserts: { of: 'cells', equals: 'answer' },
        },
      ),
    },
    ge(12, 3, 'prompted', 'A stall stands 9 jars on a shelf with 6 conkers in every jar. How many conkers are on the shelf?', [
      { childDo: 'Take the ten-jar count first, hand one jar back, and check the two digits of what you land on.', expected: '54' },
    ], '54'),
    {
      // Independent stage: no picture at all. Deciding which numbers are counting
      // plums IS the task here, so drawing the boxes would sort the story for the
      // child before they had read it.
      ...ge(12, 4, 'independent', 'A grower packs 8 plums into every box. The market stall opens at 9 o\'clock with 6 boxes on the table and 5 loose plums in a bowl beside them. How many plums has the stall got altogether? Solve cold.', [
        { childDo: 'Work out what the boxes hold before you go near anything else, and leave alone any number that is not counting plums.', expected: '53' },
      ], '53'),
    },
  ],
  days: [
    // Day 1 — concept echo: both routes in three situations, single-step only,
    // with the anchor item handing over its ten-group block as a drawn given.
    [
      { gen: wAdd, diff: 2 },
      { gen: wDivFacts, diff: 2 },
      { gen: wTenFact, diff: 2 },
      { gen: sitParkTrain, diff: 2 },
      { gen: sitSkittleFrames, diff: 3 },
      { gen: sitPizzaSlices, diff: 3 },
    ],
    // Day 2 — fluency + application: the route decision made before any
    // arithmetic, the size of the give-back as a trap, and the first chain.
    [
      { gen: wSub, diff: 2 },
      { gen: wFourFact, diff: 2 },
      { gen: sitFeedSacksEstimate, diff: 3 },
      { gen: discrimGiveOneBack, diff: 3 },
      { gen: msPosterRun, diff: 4 },
      { gen: sitSkittleFrames, diff: 3 },
    ],
    // Day 3 — interleave: the two patterns against each other, the give-back
    // trap again, and two chains, so the page shape never announces which of the
    // week's two routes is coming.
    [
      { gen: wDivFacts, diff: 2 },
      { gen: discrimWhichRow, diff: 3 },
      { gen: discrimGiveOneBack, diff: 4 },
      { gen: msSwimGala, diff: 4 },
      { gen: sitPizzaSlices, diff: 3 },
      { gen: msPlumBoxes, diff: 4 },
    ],
    // Day 4 — word problems: all three chains, including the one carrying a
    // number to leave alone, with two single-step facts mixed in so "it must be
    // two steps" never becomes the cue the child reads instead of the story.
    [
      { gen: msPosterRun, diff: 4 },
      { gen: msSwimGala, diff: 5 },
      { gen: msPlumBoxes, diff: 5 },
      { gen: sitFeedSacksEstimate, diff: 4 },
      { gen: sitParkTrain, diff: 4 },
    ],
    // Day 5 — non-computational: the pattern-slip error-analysis, the proof of
    // the digit pattern, the two rows read as patterns, and the claim that runs
    // the digit rule backwards (+ a ramped warm-up).
    [
      { gen: wSub, diff: 2 },
      { gen: eaPatternSlip, diff: 4 },
      {
        gen: reasoning({
          prompt:
            'Write any nines fact out as a ten-count with one whole group given back. Say what the ten-count puts in the tens place, then say what giving the group back does to the tens digit and what it does to the ones digit. Finish by saying why the two digits of a nines answer have no choice at all about what they add up to.',
          value:
            'the ten-count writes the number of groups in the tens place with a zero behind it; giving one group back breaks a ten open, so the tens digit drops to one below the number of groups and the ones digit becomes whatever is left of that broken ten, and those two pieces are a whole ten less one group and one group less than a ten, so together they always make nine',
          acceptableForms: ['one below', 'left of a ten', 'broken ten', 'tens digit', 'ones digit', 'make nine'],
          hints: [
            'Where does the tens digit of a nines answer come from — the number of groups, or one below it?',
            'Write a ten-count with the nines answer under it, and watch which column loses and which column picks up.',
          ],
          errorTags: ['concept-misconception', 'representation-misread'],
        }),
        diff: 4,
      },
      {
        gen: reasoning({
          prompt:
            'Write out the eights row and the nines row, as far as ten of each. Write down one thing that is true of every answer in the eights row, and one thing that is true of every answer in the nines row. Then write one sentence saying how a mark like that can tell you an answer is wrong without your working the fact out again.',
          value:
            'every eights answer is even because it was reached by doubling, and the two digits of every nines answer add up to nine; a mark like that can only tell you an answer is wrong, and it does it without the fact being worked out a second time',
          acceptableForms: ['even', 'add up to nine', 'digits', 'doubling', 'wrong'],
          keywords: true,
          hints: [
            'What do all the answers in one of these two rows have in common?',
            'Write both rows out to the end, then read down each list on its own and say what never changes about it.',
          ],
          errorTags: ['representation-misread', 'concept-misconception'],
        }),
        diff: 3,
      },
      {
        gen: classify({
          prompt:
            'Always, sometimes or never true: if the two digits of a two-digit number add up to nine, that number is one you say when you count in nines. In one sentence, say how you know.',
          correct: 'always',
          distractors: [
            {
              text: 'sometimes',
              errorTag: 'concept-misconception',
              rationale: 'Treats the digit mark as something a few of the answers happen to do, when it is what giving a group back from a ten-count does every time.',
            },
            {
              text: 'never',
              errorTag: 'representation-misread',
              rationale: 'Reads a rule about the two digits as belonging to some other count, so a number that passes the digit check is put outside the nines altogether.',
            },
          ],
          hints: [
            'How many two-digit numbers are there whose digits come to nine — a handful, or too many to write down?',
            'Write down every two-digit number whose digits make nine, and check each one of them against the count in nines.',
          ],
          errorTags: ['concept-misconception', 'representation-misread'],
        }),
        diff: 4,
      },
    ],
  ],
  teacherNoteStrips: [
    undefined,
    undefined,
    undefined,
    undefined,
    'For grown-ups: the eights and nines are the rows children say they will never learn, and they are the two that need learning least. If 9 × 7 draws a blank, do not supply 63 — ask "what is 10 × 7?" and then "so what has to come back off?". Two easy questions get there every time. The digit check is worth teaching as a habit rather than a trick: a child who adds the two digits of a nines answer before writing it down catches their own slip, which is a different and much better feeling than being told they are wrong.',
  ],
  puzzle: (r) => {
    // A row of the nines count copied off the board with ONE number spoiled. The
    // new move is REPAIR, and the evidence is the row itself: the spoiled number
    // breaks both the step between neighbours and the digit mark, and neither of
    // those needs a multiplication to see. Deterministic construction, never a
    // redraw loop (kit §E2.4).
    const len = r.int(8, NINES_MAX);
    const spoiled = r.int(3, len - 1);
    const good = 9 * spoiled;
    const bad = good + 1;
    const row = Array.from({ length: len }, (_, i) => (i + 1 === spoiled ? bad : 9 * (i + 1)));
    const name = one(r);
    return {
      id: 'C12-PZ-01',
      title: 'Puzzle Grove: The Spoiled Row',
      puzzleType: 'pattern',
      prompt: `${name} copies the nines row off the board and gets one of the numbers wrong: ${row.join(', ')}. Write down the number that has been copied wrongly and the number that belongs in its place, and then say how the row itself told you which one it was — without any multiplying.`,
      answer: {
        // A `set`, not a single value: the task is to name the spoiled number AND
        // repair it, and a child who does only one half has not finished the job.
        value: `${bad}, ${good}`,
        acceptableForms: [`${bad}; ${good}`, `${bad} ${good}`],
        validation: 'set',
      },
      hintLadder: [
        'How much does this row grow by as your eye travels from one number to the number beside it?',
        'Add the two digits of each number in turn, and stop at the one that does not behave like its neighbours.',
      ],
      errorTags: ['representation-misread', 'procedure-slip'],
    };
  },
  puzzleMeta: { stepCount: 2, cognitiveOp: 'pattern-repair' },
  sprint: {
    skill: 'Multiplication facts ×2 to ×5 — the doublings an eights fact is built from',
    sourceWeek: C8,
    itemCount: 18,
    scheduledDay: 2,
    templateId: 'mult_facts_v1',
    params: { factorRange: [2, 5] },
  },
  mastery: [
    { gen: sitParkTrain, diff: 3 },
    { gen: msPosterRun, diff: 3 },
    { gen: sitSkittleFrames, diff: 3 },
    { gen: msSwimGala, diff: 4 },
    { gen: sitPizzaSlices, diff: 3 },
    { gen: msPlumBoxes, diff: 4 },
  ],
  isomorphNotes:
    'Pairs by index; same generator and difficulty per slot, fresh operands off a separate stream. 01/03/05: single-step eights and nines — a part-whole whose ten-group count is already made and drawn, a real nine carried by a skittle frame, and an eights fact carried by an object that performs its own doubling — with the ten-group figure affordance preserved on the first. 02/04/06: the three chains — the give-back run as a ten-hour print run, the eights fact followed by a compare, and the stall chain carrying a time of day that never enters the working. No operand surface reused from Form A or from the daily pages.',
  mistakeBank: [
    {
      errorTag: 'concept-misconception',
      subtype: 'one-back-not-one-group',
      description: 'Reaches a nines fact from the ten-count and gives back a single one where a whole group belonged, so the answer lands just under the ten-count instead of one group under it.',
      exampleWrongAnswer: '9 jars of 7 conkers answered as 69',
      distractorRationale: 'Offer the ten-count with one taken off it.',
      reteachPointer: 'explanation/script[0] (one seven comes off seventy, not one crocus)',
    },
    {
      errorTag: 'representation-misread',
      subtype: 'wrong-sized-give-back',
      description: 'Gives back the number of GROUPS rather than what one group holds, or reads an answer off the row next door, so the step away from the ten-count is the wrong size.',
      exampleWrongAnswer: '9 lanes of 6 skittles answered as 50',
      distractorRationale: 'Offer the ten-count with the number of groups taken off it.',
      reteachPointer: 'explanation/script[1] (what leaves the ten-count is one whole group of the size the story names)',
    },
    {
      errorTag: 'procedure-slip',
      subtype: 'digits-out-of-step',
      description: 'Runs the two digit patterns of the nines row out of step with each other — the tens digit right, the ones digit taken one place too far down — so the answer lands exactly one below the truth and its digits no longer make nine.',
      exampleWrongAnswer: '9 × 7 answered as 62',
      distractorRationale: 'Offer the true product with one taken off it.',
      reteachPointer: 'explanation/script[3] (the digit check catches the answer that is a single step out)',
    },
    {
      errorTag: 'task-comprehension',
      subtype: 'stops-at-the-friendly-count',
      description: 'Answers with the ten-count or the four-count the story handed over, so the give-back or the doubling that finishes the fact never happens.',
      exampleWrongAnswer: 'a ten-carriage train with one carriage roped off answered with the whole ten-carriage count',
      distractorRationale: 'Offer the friendly count the story already stated.',
      reteachPointer: 'guidedExamples/C12-GE-01 (the fact is only finished once the group has gone back)',
    },
    {
      errorTag: 'fact-recall',
      subtype: 'no-route-back',
      description: 'Hunts for a remembered eights or nines fact and guesses at a near number when it will not come, rather than starting from the ten-count or the four-count.',
      exampleWrongAnswer: '8 × 7 answered as 54',
      distractorRationale: 'Offer a near-miss product of the kind an unsure recall produces.',
      reteachPointer: 'guidedExamples/C12-GE-02 (name the easy fact first, then double it), then the 2-minute doublings sprint',
    },
  ],
  parentSummarySeed: {
    whatWeWorkedOn:
      'The ×8 and ×9 facts, built rather than memorised. Nine of something is ten of it with one group handed back, and eight of something is a four-count doubled. This week practised both routes, and the check that comes free with the nines: the two digits of every nines answer add up to nine.',
    improvingCandidates: [
      'reaching a nines fact from the ten-count instead of guessing at it',
      'handing back a whole group rather than a single one',
      'checking an answer with its own two digits before writing it down',
    ],
    strengtheningByTag: [
      {
        errorTag: 'concept-misconception',
        text: 'the size of the give-back — one whole group off the ten-count, not one single thing',
      },
      {
        errorTag: 'representation-misread',
        text: 'telling the number of groups apart from what one group holds, and telling the eights row from the nines row',
      },
      {
        errorTag: 'procedure-slip',
        text: 'keeping the two digit patterns of the nines row in step, so an answer does not land one below the truth',
      },
      {
        errorTag: 'task-comprehension',
        text: 'finishing the rebuild rather than handing back the friendly count the story already gave',
      },
      {
        errorTag: 'fact-recall',
        text: 'reaching for the ten-count or the four-count when a hard fact will not come',
      },
    ],
    homeFocus: {
      praiseLine:
        'You counted ten of them and handed one whole group back, and then you checked the two digits before you wrote the answer down — that check is the habit this whole week is built on.',
      questionForChild: 'What is 10 times 7? So what is 9 times 7 — and what did you have to give back to get there?',
      schoolSyncHook: 'If your child\'s class is learning the eights and nines as rows to recite rather than as facts to build, tell us and we will practise them both ways.',
    },
    vocabularyForParent: [
      'ten-count (ten of something — the easiest count there is)',
      'give a group back (overshoot to ten groups, then take one whole group off)',
      'digit check (the two digits of a nines answer always add up to nine)',
    ],
  },
});
