/**
 * Level E · Week 1 — "Ratios" (conceptId: ratios).
 *
 * The Level-E v2 EXEMPLAR. FILL-ARCHITECTURE §6 row E1: anchor "the ratio table
 * as a structure-preserving machine"; key multi-step "scale then compare
 * recipes"; error-analysis "adds the same number to both terms"; discrimination
 * "additive vs multiplicative growth"; Day-5 signature "which is more lemony —
 * a defence".
 *
 * The week's whole claim is that a ratio names a RELATIONSHIP and not a pair of
 * sizes, so the only edit it survives is one that multiplies both terms by the
 * same factor. Everything below is built to force that distinction rather than
 * announce it:
 *  - two discriminations that attack the additive misconception from opposite
 *    sides. `additiveVsMultiplicativeGrowth` asks the child to PRODUCE the term
 *    that keeps a mix the same; the row-integrity item asks them to DETECT the
 *    one pair among three that cannot have come from a table — and the impostor
 *    row is generated by the family's own `additiveScalingTerm`, so it is the
 *    genuine output of the misconception. The two rationales on that item are
 *    the same error seen from the other end: an additive reader keeps the row
 *    whose GAP is unchanged and rejects the true rows, because scaling is the
 *    one move that leaves the gap alone;
 *  - a generated error-analysis (`eaScaleByAdding`) whose shown wrong number is
 *    a real misconception output, re-derived by QG-11;
 *  - six genuine multi-step items across four shapes: combine-then-scale,
 *    scale-then-compare (the recipe's headline, and the arithmetic the Day-5
 *    defence rests on), scale-then-add-an-unscaled-extra, and an inverse-start
 *    chain that has to undo a scaling before it can total anything;
 *  - the three Level-E ceiling lifts, each carried by a different item:
 *    INVERSE-START (the compost batch: the stated quantity is the RESULT of the
 *    scaling), HAS-DISTRACTOR (the dough: the loaf count is stated and never
 *    used — dividing by it is the seductive extra step), and CHECK-BACK (the
 *    same compost item, wrapped: the honest check on an unscaled answer is
 *    whether the pair you wrote still stands in the recipe's ratio).
 *
 * FIGURE LAW as applied here (FANOUT kit §F.7 / §E2.5): every figure on a DAY
 * ITEM shows what the child was HANDED — the opening row of a table with the
 * asked cell left as '?', the two bars of the ratio before any scaling — and is
 * built from the item's own drawn params. The pictures that show a completed
 * journey live where the answer is already on the page: the lesson script and
 * the guided examples.
 *
 * TWO AUTHORING DECISIONS, recorded here rather than buried (§E2.3 convention):
 *
 *  1. `partWholeVsPartPart` is NOT served, although it is one of the family's
 *     E1 generators. It draws from the same COLLECTIONS pool as
 *     `partToWholeShare` and opens with the same sentence ("A box holds P gold
 *     beads for every Q glass beads…"), so a week carrying both prints one
 *     sentence twice with new numbers. `partToWholeShare` is kept — it computes
 *     the share rather than choosing it — and the part:part↔part:whole reading
 *     is carried instead by the Day-5 vocabulary and the parent note.
 *
 *  2. The ratio table is drawn with `areaGrid` (two columns, cell labels) and
 *     ships WITHOUT an `asserts` clause. The figure library has no table
 *     primitive, and area-grid's assertable quantities — `shaded` and `cells` —
 *     name nothing a table cell means, so an assertion here would audit the
 *     wrong number. The picture is still built from the item's own params by
 *     construction (`withFigure` reads `generator.params`), and it shows only
 *     given cells plus a '?' where the question is.
 *
 * Retrieval is backward-only into the four Level-D skills a ratio actually runs
 * on: D9 equivalence by scaling (the direct ancestor — top and bottom grow by
 * the same factor), D4 "times as many", D16 exact division (the move that
 * recovers a scale factor) and D15 multiplication fluency.
 */

import { asWarmup, classify, divideExact, fracEquivFill, multiply, reasoning, storyMulCompare } from '../lib/items';
import type { ItemGen } from '../lib/items';
import { situation } from '../lib/situations';
import { multiStep } from '../lib/multistep';
import { discrimination } from '../lib/discrimination';
import { withCheckBack, withEstimateFirst } from '../lib/metacog';
import { countNoun } from '../lib/format';
import { makeGe, makeWeekBuilder } from '../lib/assemble';
import { areaGrid, barModel } from '../lib/figures';
import {
  additiveScalingTerm,
  additiveVsMultiplicativeGrowth,
  eaScaleByAdding,
  equivalentRatioFill,
  msCombineThenScale,
  partToWholeShare,
  ratioTableCell,
} from '../lib/ratio';
import type { BBFigure } from '../../../figures/types';
import type { Rng } from '../../rng';

const ge = makeGe('E');

const C12 = { level: 'C' as const, week: 12 };
const D4 = { level: 'D' as const, week: 4 };
const D9 = { level: 'D' as const, week: 9 };
const D15 = { level: 'D' as const, week: 15 };
const D16 = { level: 'D' as const, week: 16 };

const NAMES = ['Maya', 'Leo', 'Ava', 'Ben', 'Mia', 'Sam', 'Ria', 'Noor', 'Ken', 'Pia', 'Tom', 'Zoe'] as const;
/** One drawn name. Never hardcode a name that is also in this pool (kit §F.3). */
const one = (r: Rng): string => r.pick(NAMES);

// ---------------------------------------------------------------------------
// withFigure — attach a picture built from the item's OWN generator params.
//
// The shipped primitives have no figure slot and lib/ is not ours to edit, so
// this wrapper does what `withEstimateFirst` does: all work happens inside the
// returned closure, no new rng draw is taken, and the prompt (and therefore the
// QG-1/QG-4 surface signature) is untouched. It reads the drafted item's
// `generator.params` — the very numbers the answer was computed from — so the
// figure law holds by construction. (Pattern copied from c05/c06.)
// ---------------------------------------------------------------------------

type Params = Record<string, unknown>;
const numOf = (p: Params, k: string): number => Number(p[k]);

function withFigure(base: ItemGen, build: (params: Params) => BBFigure): ItemGen {
  return (rng, guard, difficulty) => {
    const d = base(rng, guard, difficulty);
    return d.generator ? { ...d, figure: build(d.generator.params) } : d;
  };
}

// ---------------------------------------------------------------------------
// Retrieval warm-ups (strictly earlier weeks; exempt from the pedagogy gates)
// ---------------------------------------------------------------------------

/** D9 — equivalence by scaling. Top and bottom grow by the same factor; that is
 *  this week's rule, one year early and wearing a fraction bar. */
const wEquivFrac = asWarmup(fracEquivFill(), D9);
/** D4 — "times as many", the language a ratio is about to compress into a pair. */
const wTimesAsMany = asWarmup(storyMulCompare(), D4);
/** D16 — exact division, the move that recovers a scale factor from a later row. */
const wUnscale = asWarmup(divideExact(3, 12, 4, 14), D16);
/** D15 — the product itself, so scaling a row never stalls on the arithmetic. */
const wProduct = asWarmup(multiply(3, 14, 4, 25), D15);

// ---------------------------------------------------------------------------
// Single-step ratio situations
//
// Three come from the G4 family: the equivalent-ratio fill (with the family's
// own two-bar figure), the ratio-table cell, and the part-to-whole share. The
// fourth is local: a scale drawing, which is the same rule wearing units the
// child has never seen it in — and it is the week's estimate-first carrier, so
// it is only ever reachable through the wrapper (§E2.2).
// ---------------------------------------------------------------------------

/** The anchor item, with a two-column ratio table drawn from its own params. */
const sitTableCell = withFigure(ratioTableCell(), (p) => {
  const a = numOf(p, 'a');
  const b = numOf(p, 'b');
  const x = numOf(p, 'x');
  return areaGrid(
    {
      rows: 2,
      cols: 2,
      colLabels: ['litres of paint', 'square metres'],
      cellLabels: [String(a), String(b), String(x), '?'],
    },
    {
      alt: `a two-column ratio table whose first row pairs ${countNoun(a, 'litres')} of paint with ${countNoun(b, 'square metres')}, and whose second row shows ${countNoun(x, 'litres')} of paint beside an empty cell`,
    },
  );
});

/**
 * A scale drawing: the same relationship in centimetres and metres, where the
 * two terms are not even measured in the same unit and so cannot be compared by
 * subtraction at all. Served ONLY through the estimate-first wrapper.
 */
const sitPlanScale = situation({
  situationType: 'measurement',
  cognitiveOp: 'ratio-scale',
  draw: (r) => {
    const realM = r.int(2, 6);
    const planCm = r.int(3, 9);
    const k = r.int(3, 8);
    return {
      prompt: `On an architect's plan, ${countNoun(planCm, 'cm')} of drawing stands for every ${countNoun(realM, 'm')} of the real hall. One wall of the hall measures ${countNoun(realM * k, 'm')}. How long is that wall on the plan?`,
      answerValue: String(planCm * k),
      templateId: 'ratio_equivalent_v1',
      params: { a: realM, b: planCm, k, want: 'second' },
      units: 'cm',
      hints: [
        'Does a scale drawing shrink every real length by the same factor, or take a fixed amount off each one?',
        'Work out how many times the stated real length fits into the wall, then take the drawn length that many times.',
      ],
      errorTags: ['concept-misconception', 'representation-misread'],
    };
  },
});
const sitPlanScaleEstimate = withEstimateFirst(
  sitPlanScale,
  'will the wall on the plan come out a few centimetres longer than the drawn length the scale names, or several times as long?',
);

// ---------------------------------------------------------------------------
// Multi-step: four shapes, so "two steps" never becomes a single template
// ---------------------------------------------------------------------------

/**
 * THE RECIPE'S HEADLINE (§6 row E1, "scale then compare recipes"). Two mixes
 * are written for different numbers of lemons, so they cannot be compared as
 * they stand: the first has to be grown to the second's lemon count before the
 * two amounts of water mean anything beside each other. The chain is therefore
 * scale, then compare — and the answer is the gap the scaling reveals.
 *
 * The draw fixes the second recipe to be the LEMONIER of the two (its water is
 * short of the scaled-up first recipe by a positive amount), which is what
 * makes the Day-5 defence a real defence: the jug with more lemons in it is not
 * the strong one.
 */
const msScaleThenCompare = multiStep({
  situationType: 'comparison',
  cognitiveOp: 'ratio-compare',
  draw: (r) => {
    // Water outruns lemons in both recipes, so neither jug is a syrup: the
    // second recipe's stated water is bounded below by its own lemon count.
    const lemons = r.int(2, 5);
    const cups = lemons + r.int(1, 5);
    const k = r.int(3, 6);
    // short ≥ 2, so the two recipes never coincide and the answer is never a
    // count of one (which would print "1 cups" through countNoun). The upper
    // bound keeps the second recipe's water strictly above its lemon count,
    // so neither jug in the story is a syrup. (cups − lemons) · k ≥ 3, so the
    // range never inverts.
    const short = r.int(2, Math.min(6, (cups - lemons) * k - 1));
    const rival = cups * k - short;
    return {
      prompt: `One lemonade recipe uses ${countNoun(cups, 'cups')} of water for every ${countNoun(lemons, 'lemons')}. A second recipe uses ${countNoun(rival, 'cups')} of water with ${countNoun(lemons * k, 'lemons')}. Scaled up to ${countNoun(lemons * k, 'lemons')} with its ratio unchanged, how many more cups of water does the first recipe need than the second?`,
      initN: cups,
      steps: [
        { op: 'mul', n: k, d: 1 },
        { op: 'sub', n: rival, d: 1 },
      ],
      units: 'cups',
      hints: [
        'Can two recipes be judged against each other while one of them is written for fewer lemons than the other?',
        'Grow the first recipe until its lemons match the second recipe\'s, then set the two amounts of water side by side.',
      ],
      errorTags: ['concept-misconception', 'task-comprehension'],
    };
  },
});

/**
 * INVERSE-START (PEDAGOGY-CEILING-REVIEW F3, the Level-E lift). The quantity the
 * story hands over is the RESULT of the scaling, not one of the recipe's own
 * numbers, so the opening move is a division nothing in the sentence order asks
 * for: find how many times the recipe was taken, and only then build the batch.
 *
 * Served through the check-back wrapper, because the honest check on an undone
 * scaling is not "is the arithmetic right" but "does the pair I ended with
 * still stand in the recipe's ratio" — which is the week's rule used backwards.
 */
const msUnscaleThenTotal = multiStep({
  situationType: 'part-whole',
  cognitiveOp: 'ratio-unscale',
  posing: 'inverse-start',
  usesPriorSkill: true,
  draw: (r) => {
    const grit = r.int(2, 5);
    // loam > grit, so the recipe is never 1 : 1 (where scaling and adding
    // would be indistinguishable in the answer, not just in the child's head).
    const loam = grit + r.int(1, 4);
    const k = r.int(3, 7);
    return {
      prompt: `A batch of potting compost used ${countNoun(loam * k, 'litres')} of loam. It was mixed to a recipe of ${countNoun(grit, 'litres')} of grit for every ${countNoun(loam, 'litres')} of loam. How many litres of grit and loam went into the batch altogether?`,
      initN: loam * k,
      steps: [
        { op: 'div', n: loam, d: 1 },
        { op: 'mul', n: grit, d: 1 },
        { op: 'add', n: loam * k, d: 1 },
      ],
      units: 'litres',
      hints: [
        'Does the amount of loam in this story come from the recipe line, or from the recipe already scaled up?',
        'Work out how many times the recipe was taken, then build both parts of the batch from that.',
      ],
      errorTags: ['concept-misconception', 'procedure-slip'],
    };
  },
});
const msUnscaleThenTotalCheck = withCheckBack(
  msUnscaleThenTotal,
  'do the two amounts you have found stand in the same ratio the recipe names?',
);

/**
 * HAS-DISTRACTOR (PEDAGOGY-CEILING-REVIEW F3). Two things separate this from the
 * combine-then-scale chain: the order is reversed (scale first, then add), and
 * the amount added afterwards is NOT part of the ratio, so it must not be
 * scaled with it. The number of loaves is stated and never used — and it is the
 * seductive kind of spare quantity, because dividing by it is a move the story
 * almost invites.
 */
const msScaleThenAdd = multiStep({
  situationType: 'multi-stage',
  cognitiveOp: 'ratio-scale-then-add',
  posing: 'has-distractor',
  draw: (r) => {
    // Water is drawn AS A SHARE of the flour — 40% to 70%, the hydration range
    // a real dough lives in — so the ratio the item scales is one a baker would
    // recognise. Flour is a multiple of 50, so the share is always whole.
    const flour = r.int(2, 3) * 50;
    const water = (flour * r.int(4, 7)) / 10;
    const k = r.int(3, 6);
    const extra = r.int(2, 9) * 5;
    const loaves = r.int(3, 8);
    const name = one(r);
    return {
      prompt: `A bread dough uses ${countNoun(water, 'grams')} of water for every ${countNoun(flour, 'grams')} of flour. ${name} mixes a dough with ${countNoun(flour * k, 'grams')} of flour, then works in another ${countNoun(extra, 'grams')} of water to soften it. The dough is shaped into ${countNoun(loaves, 'loaves')}. How much water goes into the dough in all?`,
      initN: water,
      steps: [
        { op: 'mul', n: k, d: 1 },
        { op: 'add', n: extra, d: 1 },
      ],
      units: 'grams',
      hints: [
        'Which amount in this story grows with the flour, and which one is simply tipped in afterwards?',
        'Scale the water that belongs to the flour first, then bring in what was added later — and leave alone the number that counts something else.',
      ],
      errorTags: ['task-comprehension', 'representation-misread'],
    };
  },
});

// ---------------------------------------------------------------------------
// Discrimination — the additive misconception, from both ends
// ---------------------------------------------------------------------------

/**
 * Row integrity: three pairs are offered as later rows of one table, and the
 * impostor is the row the ADDITIVE scaler writes — `additiveScalingTerm`, the
 * family's own code for the misconception, supplies its second term.
 *
 * The two distractor rationales are the same error read from the other side.
 * Adding a fixed amount to both terms is the one move that PRESERVES the gap
 * between them, so the impostor row is the only one whose two numbers are still
 * the original distance apart — which is exactly why a child reasoning by gaps
 * keeps it and throws out the genuine rows instead.
 */
const discrimRowIntegrity = discrimination({
  variant: 'structural',
  cognitiveOp: 'ratio-table-integrity',
  draw: (r) => {
    const a = r.int(2, 6);
    // b > a, so "same gap" and "same ratio" cannot agree, and k ≥ 4 keeps the
    // impostor's first term clear of the two genuine rows on offer.
    const b = a + r.int(1, 5);
    const k = r.pick([4, 5]);
    return {
      prompt: `One ratio table begins with the row ${a} : ${b}. Three more pairs are offered as later rows of it. Which pair could NOT belong?`,
      correct: `${a * k} : ${additiveScalingTerm(a, b, k)}`,
      distractors: [
        {
          text: `${2 * a} : ${2 * b}`,
          errorTag: 'concept-misconception',
          rationale: 'A genuine row — both terms doubled. It is thrown out by a reader who tests whether the two numbers changed by the same AMOUNT, which no scaled row ever does.',
        },
        {
          text: `${3 * a} : ${3 * b}`,
          errorTag: 'representation-misread',
          rationale: 'Also a genuine row — both terms tripled. It is thrown out by a reader who expects the gap between the two numbers to stay put, and this is the row whose gap has grown the most.',
        },
      ],
      hints: [
        'How could you test a single pair, on its own, to see whether it belongs to a table?',
        'Reduce each pair to its simplest form and set the three results beside the opening row.',
      ],
      errorTags: ['concept-misconception', 'representation-misread'],
    };
  },
});

// ---------------------------------------------------------------------------
// The week
// ---------------------------------------------------------------------------

export const buildE01 = makeWeekBuilder({
  level: 'E',
  week: 1,
  conceptId: 'ratios',
  conceptName: 'Ratios',
  strandTags: ['multiplication-division', 'decimals-fractions'],
  prerequisiteWeeks: [D4, D9, D16],
  pedagogyContract: 'v2',
  conceptualAnchor: 'the ratio table as a structure-preserving machine',
  conceptFamily: 'operation',
  deepeningDelta:
    'D4 compared two quantities and named how many times one held the other; D9 renamed a single fraction by scaling top and bottom together. E1 makes that scaling the object of study rather than the method: a ratio is carried forward through a whole table of rows, each row has to be provable from the first, and the comparison the week ends on is between two RELATIONSHIPS, neither of which can be read off either quantity alone.',
  explanation: {
    hook:
      'Add a lemon to the jug and the drink turns sharper. Add a lemon and a cup of water and it may taste exactly as it did. This week is about which edits a mixture survives — and the answer is never about how much you added.',
    whyBeforeHow:
      'A ratio fixes the relationship between two quantities and says nothing about their sizes, so the only edit that leaves it intact is one that multiplies both terms by the same factor. Adding the same amount to each term does not work, because a fixed amount is a different share of a small quantity than of a large one — it shifts the relationship every time the two terms start out unequal. That is why we work with the ratio table as a structure-preserving machine: every row is the first row taken some whole number of times, so every row can be divided back down to the pair it came from. Reading a table across is scaling. Reading a row back down its own column is testing whether the structure held. A row that was reached by adding fails that test, and it fails it in a way you can see.',
    script: [
      {
        say: 'Watch me scale a mix. Two caps of syrup to five cups of water — that is one mix. I want three mixes, so I take three copies of the syrup and three copies of the water. Both parts are copied, and neither one is copied more times than the other. That is the whole move.',
        visual: 'The one-mix pair of bars, and beneath it the same pair taken three times.',
        figure: barModel(
          [
            { label: 'syrup, one mix', segments: [{ value: 2, label: '2' }] },
            { label: 'water, one mix', segments: [{ value: 5, label: '5' }] },
            { label: 'syrup, three mixes', segments: [{ value: 2 }, { value: 2 }, { value: 2 }], total: '6' },
            { label: 'water, three mixes', segments: [{ value: 5 }, { value: 5 }, { value: 5 }], total: '15' },
          ],
          { scaleMax: 15, alt: 'a bar of 2 for the syrup and a bar of 5 for the water, and beneath them three copies of each, making 6 and 15' },
        ),
      },
      {
        say: 'Now the edit that looks the same and is not. Adding four to each part takes the syrup to six as well — but it takes the water only to nine, and the tripled mix wanted fifteen. The syrup was tripled by that addition; the water was barely touched. One added amount, two very different effects, and the drink is a different drink.',
        visual: 'The water bar of the tripled mix beside the shorter water bar left by adding four to each part.',
        figure: barModel(
          [
            { label: 'water when both parts are tripled', segments: [{ value: 5 }, { value: 5 }, { value: 5 }], total: '15' },
            { label: 'water when four is added to each part', segments: [{ value: 5, label: '5' }, { value: 4, label: '4', fill: 'hatch' }], total: '9' },
          ],
          { scaleMax: 15, alt: 'a bar of 15 for the tripled water beside a shorter bar of 9, made of 5 with 4 added on' },
        ),
      },
      {
        say: 'Here is the machine that keeps all of this straight. Every row of a ratio table is the first row taken some number of times, so I can walk down it in any order I like, and I can always walk a row back up to the first row to prove it belongs. Nothing in the table is remembered; everything in it is recoverable.',
        visual: 'A two-column ratio table for the syrup mix, four rows deep.',
        figure: areaGrid(
          {
            rows: 4,
            cols: 2,
            colLabels: ['syrup (caps)', 'water (cups)'],
            cellLabels: ['2', '5', '4', '10', '6', '15', '10', '25'],
          },
          { alt: 'a two-column ratio table with the rows 2 and 5, 4 and 10, 6 and 15, and 10 and 25' },
        ),
      },
      {
        say: 'One habit before any of the arithmetic: I estimate the size I expect. Fourteen caps is seven times the two caps in the first row, so the water has to land near seven times five — somewhere in the thirties. If my answer came out near five, or near twenty, I did not scale, I added, and I check my working before I check anything else.',
        visual: 'The table with a new row opened for fourteen caps and its water cell still empty.',
        figure: areaGrid(
          {
            rows: 2,
            cols: 2,
            colLabels: ['syrup (caps)', 'water (cups)'],
            cellLabels: ['2', '5', '14', '?'],
          },
          { alt: 'a two-column ratio table showing the first row, 2 and 5, and a new row for 14 caps whose water cell is empty' },
        ),
      },
    ],
    summary:
      'A ratio names a relationship, not a pair of sizes. Multiply both terms by the same factor and the relationship survives; add the same amount to both and it does not, unless the terms were already equal. A ratio table writes that rule down: every row is the first row taken some number of times, so any row can be divided back to prove it belongs.',
    vocabulary: [
      { term: 'ratio', kidGloss: 'a fixed relationship between two quantities, written a : b' },
      { term: 'equivalent ratios', kidGloss: 'two ratios that describe the same relationship, because one is the other with both terms multiplied by the same factor' },
      { term: 'ratio table', kidGloss: 'a table whose every row is the first row multiplied by some factor, so every row carries the same relationship' },
      { term: 'scale factor', kidGloss: 'the number both terms are multiplied by to reach a later row' },
      { term: 'part-to-whole', kidGloss: 'a comparison of one part with the total of all the parts — the comparison a fraction names' },
    ],
  },
  guidedExamples: [
    {
      ...ge(1, 1, 'modeled', 'A ratio table pairs 3 litres of paint with 8 square metres of wall in its first row. A later row shows 12 litres of paint. How many square metres does that row pair with?', [
        {
          teacherSay:
            'Watch what I settle before I write anything down. The first row pairs three litres with eight square metres, and the row I am asked about holds twelve litres. So my question is not how many MORE litres this row has — it is how many TIMES as many?',
        },
        {
          teacherSay: 'Three litres taken four times is twelve, so the whole row has been taken four times. What does four copies make of the eight square metres?',
          expected: '32',
        },
      ], '32'),
      visual: 'The two-row table with both cells of the later row filled in.',
      figure: areaGrid(
        {
          rows: 2,
          cols: 2,
          colLabels: ['litres of paint', 'square metres'],
          cellLabels: ['3', '8', '12', '32'],
        },
        { alt: 'a two-column ratio table pairing 3 litres with 8 square metres, and 12 litres with 32 square metres' },
      ),
    },
    {
      ...ge(1, 2, 'completion', 'A ratio table begins with the row 4 : 9. Two pairs are offered as a later row of it: 12 : 17 and 12 : 27. Which one belongs to the table?', [
        {
          teacherSay: 'What has to stay the same as a table runs down the page — the gap between the two numbers, or the number of times one of them fits into the other?',
          expected: 'the number of times one fits into the other',
        },
        { childDo: 'Divide each offered pair down to its simplest form and keep the one that lands on the opening row.', expected: '12 : 27' },
      ], '12 : 27'),
      visual: 'The opening row of the table, with the later row left open.',
      figure: areaGrid(
        {
          rows: 2,
          cols: 2,
          colLabels: ['first term', 'second term'],
          cellLabels: ['4', '9', '12', '?'],
        },
        { alt: 'a two-column ratio table showing the opening row, 4 and 9, and a later row whose first term is 12 and whose second term is empty' },
      ),
    },
    ge(1, 3, 'prompted', 'A cleaning solution uses 2 caps of concentrate for every 5 litres of water. How many litres of water go with 8 caps?', [
      { childDo: 'Find what the concentrate was multiplied by, then apply that same factor to the water.', expected: '20' },
    ], '20'),
    {
      // Independent stage: the recipe pair ONLY. Deciding to undo the scaling
      // before totalling anything IS the task here, so drawing the batch would
      // hand the child the plan the item exists to ask for (L33).
      ...ge(1, 4, 'independent', 'A batch of potting compost used 24 litres of loam. It was mixed to a recipe of 3 litres of grit for every 8 litres of loam. How many litres of grit and loam went into the batch altogether? Solve cold.', [
        { childDo: 'Undo the scaling first, then build both parts of the batch from what that gives you.', expected: '33' },
      ], '33'),
      visual: 'The recipe pair as two bars. The batch itself is yours to work out.',
      figure: barModel(
        [
          { label: 'grit in the recipe', segments: [{ value: 3, label: '3' }] },
          { label: 'loam in the recipe', segments: [{ value: 8, label: '8' }] },
        ],
        { scaleMax: 8, alt: 'a bar of 3 for the grit in the recipe beside a bar of 8 for the loam; the batch is not drawn' },
      ),
    },
  ],
  days: [
    // Day 1 — concept echo: the ratio read three ways (scale a mix, fill a table
    // row, name a share of the whole), single-step only, no two-step load yet.
    [
      { gen: wEquivFrac, diff: 2 },
      { gen: wTimesAsMany, diff: 2 },
      { gen: wUnscale, diff: 2 },
      { gen: equivalentRatioFill(), diff: 3 },
      { gen: sitTableCell, diff: 3 },
      { gen: partToWholeShare(), diff: 3 },
    ],
    // Day 2 — fluency + application: the row-integrity discrimination, the
    // estimate-first metacognition, and the week's first two-step chain.
    [
      { gen: wProduct, diff: 2 },
      { gen: wEquivFrac, diff: 2 },
      { gen: sitPlanScaleEstimate, diff: 3 },
      { gen: discrimRowIntegrity, diff: 3 },
      { gen: msCombineThenScale(), diff: 4 },
      { gen: partToWholeShare(), diff: 3 },
    ],
    // Day 3 — interleave: both discriminations against two differently-shaped
    // two-steps, so the page never signals which kind of work is coming.
    [
      { gen: wUnscale, diff: 2 },
      { gen: additiveVsMultiplicativeGrowth(), diff: 4 },
      { gen: discrimRowIntegrity, diff: 3 },
      { gen: msScaleThenCompare, diff: 4 },
      { gen: sitTableCell, diff: 3 },
      { gen: msScaleThenAdd, diff: 3 },
    ],
    // Day 4 — word problems: the compare chain, the inverse-start batch and the
    // dough with a quantity that must be left alone, plus two single-step items
    // so "it must be multi-step" never becomes the cue.
    [
      { gen: msScaleThenCompare, diff: 5 },
      { gen: msUnscaleThenTotalCheck, diff: 5 },
      { gen: msScaleThenAdd, diff: 5 },
      { gen: equivalentRatioFill(), diff: 4 },
      { gen: sitPlanScaleEstimate, diff: 4 },
    ],
    // Day 5 — non-computational: the additive-scaling error-analysis, the
    // "which is more lemony" defence, and the claim that says exactly when the
    // additive move is harmless (+ a ramped warm-up).
    [
      { gen: wTimesAsMany, diff: 2 },
      { gen: eaScaleByAdding(), diff: 4 },
      {
        gen: reasoning({
          prompt:
            'Jug A is mixed with 3 lemons to 5 cups of water. Jug B is mixed with 4 lemons to 8 cups of water. Decide which jug tastes more strongly of lemon, then write a defence of your answer that would convince someone who holds that B must be the stronger one, since it has more lemons in it. Your defence has to compare the two mixes, not the two lemon counts.',
          value: 'jug A — brought to the same number of lemons, A carries less water than B, so B holds more lemons only because it holds more of everything',
          acceptableForms: ['jug A', 'same number of lemons', 'per cup', 'less water', 'ratio', 'scale'],
          keywords: true,
          hints: [
            'Which comparison can settle a question of taste — the number of lemons, or the lemons set against the water?',
            'Rewrite both jugs with the same number of lemons, then read off which one is carrying less water.',
          ],
          errorTags: ['concept-misconception', 'task-comprehension'],
        }),
        diff: 3,
      },
      {
        gen: classify({
          prompt:
            'Always, sometimes, or never true: adding the same amount to both terms of a ratio leaves the ratio unchanged. In one sentence, say which ratios your answer holds for.',
          correct: 'sometimes',
          distractors: [
            {
              text: 'always',
              errorTag: 'concept-misconception',
              rationale: 'The additive move itself. It treats a ratio as two amounts rather than one relationship, and it changes every ratio whose terms are not already equal.',
            },
            {
              text: 'never',
              errorTag: 'task-comprehension',
              rationale: 'Over-corrects. The claim has to be tested against every ratio, including one whose two terms are already the same, where adding an equal amount to each leaves the relationship exactly as it was.',
            },
          ],
          hints: [
            'Is there any pair of numbers you could add the same amount to and still have the same relationship?',
            'Try a ratio whose two terms are already equal, then try one whose terms are not, and see whether a single verdict covers both.',
          ],
          errorTags: ['concept-misconception', 'task-comprehension'],
        }),
        diff: 4,
      },
    ],
  ],
  teacherNoteStrips: [
    undefined,
    undefined,
    undefined,
    undefined,
    'For grown-ups: the one error worth watching for this week is scaling by addition — turning 3 : 5 into 6 : 8 instead of 6 : 10. It is not carelessness; it is a reasonable rule applied to the wrong kind of quantity, and children hold it firmly. Do not correct the numbers. Ask instead whether the drink would still taste the same, and let the answer come from the taste rather than from you.',
  ],
  puzzle: (r) => {
    const juicePart = r.int(2, 4);
    const waterPart = juicePart + r.int(1, 4);
    const batches = r.int(3, 6);
    const juice = juicePart * batches;
    const rightWater = waterPart * batches;
    const shortfall = r.int(2, Math.min(8, rightWater - 4));
    const water = rightWater - shortfall;
    return {
      id: 'E1-PZ-01',
      title: 'Puzzle Grove: The Bowl That Cannot Be Fixed',
      puzzleType: 'logic',
      prompt: `A punch is mixed ${countNoun(juicePart, 'cups')} of juice to every ${countNoun(waterPart, 'cups')} of water. A bowl already holds ${countNoun(juice, 'cups')} of juice and ${countNoun(water, 'cups')} of water, and the mix is not right. Only ONE of the two liquids may be added. Say how much must go in and which liquid it is — then explain why adding the other liquid could never put this bowl right, no matter how much of it went in.`,
      answer: {
        value: `${shortfall} cups of water`,
        acceptableForms: [String(shortfall), countNoun(shortfall, 'cups'), `${shortfall} cups of water`, 'water'],
        validation: 'short-text-keyword',
      },
      hintLadder: [
        'Which of the two liquids is this bowl already carrying too much of?',
        'Work out how much water would stand beside the juice already in the bowl if the mix were right, then hold that against what is there.',
      ],
      errorTags: ['concept-misconception', 'task-comprehension'],
    };
  },
  puzzleMeta: { stepCount: 2, cognitiveOp: 'ratio-repair' },
  sprint: {
    skill: 'Single-digit multiplication facts — the factor every ratio-table row is built from',
    sourceWeek: C12,
    itemCount: 20,
    scheduledDay: 3,
    templateId: 'mult_facts_v1',
    params: { factorRange: [2, 9] },
  },
  mastery: [
    { gen: equivalentRatioFill(), diff: 3 },
    { gen: msScaleThenCompare, diff: 4 },
    { gen: sitTableCell, diff: 3 },
    { gen: msUnscaleThenTotalCheck, diff: 4 },
    { gen: partToWholeShare(), diff: 3 },
    { gen: msScaleThenAdd, diff: 4 },
  ],
  isomorphNotes:
    'Pairs by index; same generator and difficulty per slot, fresh operands off a separate stream. 01/03/05: single-step ratio work — scale a mix to a stated first term, fill a later cell of a ratio table (with the opening-row figure affordance preserved), and name one group as a share of the whole. 02/04/06: two-step and three-step chains — scale one recipe to another and compare, undo a scaling before totalling a batch (inverse-start, with the check-back frame), and scale a ratio then add a quantity that is not part of it (carrying a stated number that must be left unused). No operand surface reused from Form A or the daily pages.',
  mistakeBank: [
    {
      errorTag: 'concept-misconception',
      subtype: 'additive-scaling',
      description: 'Scales a ratio by adding the same amount to both terms instead of multiplying both by the same factor, so the relationship changes while the child believes it has been preserved.',
      exampleWrongAnswer: 'the row after 3 : 5 written as 6 : 8 rather than 6 : 10',
      distractorRationale: 'Offer the second term the additive move genuinely produces — the first term\'s increase added to the second term.',
      reteachPointer: 'explanation/script[1] (one added amount, two very different effects) beside script[0] (both parts copied the same number of times)',
    },
    {
      errorTag: 'representation-misread',
      subtype: 'reads-the-gap',
      description: 'Judges whether a pair belongs to a ratio table by the difference between its two numbers rather than by the factor between the rows, so the one row that preserves the gap is kept and the genuine rows are rejected.',
      exampleWrongAnswer: '9 : 12 accepted into the table opening 3 : 6, and 6 : 12 rejected from it',
      distractorRationale: 'Offer a genuine scaled row, which a gap-reader throws out precisely because its two numbers have moved apart.',
      reteachPointer: 'explanation/script[2] (every row walks back up to the first row), then guidedExamples/E1-GE-02',
    },
    {
      errorTag: 'task-comprehension',
      subtype: 'compares-one-quantity',
      description: 'Settles a comparison between two mixes on one quantity alone — the jug with more lemons, the pack with the lower price — instead of bringing both to a common term first.',
      exampleWrongAnswer: '4 lemons to 8 cups called stronger than 3 lemons to 5 cups, because it holds more lemons',
      distractorRationale: 'Offer the option that follows from the larger single quantity, which is the reading a comparison of relationships is meant to defeat.',
      reteachPointer: 'guidedExamples/E1-GE-01 (how many TIMES as many, not how many more), then the Day-4 scale-and-compare problems',
    },
    {
      errorTag: 'procedure-slip',
      subtype: 'factor-applied-once',
      description: 'Chooses the right move and the right factor, then applies it to only one of the two terms, or scales a quantity that was added afterwards and never belonged to the ratio.',
      exampleWrongAnswer: 'a dough scaled four times with the extra water scaled four times along with it',
      distractorRationale: 'Offer the result of scaling every number the story states, including the one that stands outside the ratio.',
      reteachPointer: 'guidedExamples/E1-GE-03 (the same factor across the row), then the 2-minute multiplication sprint',
    },
  ],
  parentSummarySeed: {
    whatWeWorkedOn:
      'Ratios — reading a pair of quantities as a relationship rather than as two amounts, scaling that relationship with ratio tables, telling scaling apart from adding the same number to both terms, and comparing two mixtures by bringing them to a common term first.',
    improvingCandidates: [
      'finding the factor between two rows of a ratio table',
      'checking a scaled row by dividing it back down to the row it came from',
      'bringing two mixtures to a common term before comparing them',
    ],
    strengtheningByTag: [
      {
        errorTag: 'concept-misconception',
        text: 'scaling by multiplying both terms rather than adding to both — the mixture pictures make the difference in taste visible at once',
      },
      {
        errorTag: 'representation-misread',
        text: 'judging a row by the factor between the rows rather than by the gap between its two numbers',
      },
      {
        errorTag: 'task-comprehension',
        text: 'comparing two mixtures on the relationship inside each, instead of on whichever single quantity is larger',
      },
      {
        errorTag: 'procedure-slip',
        text: 'carrying one factor across both terms, and leaving alone anything that was added outside the ratio',
      },
    ],
    homeFocus: {
      praiseLine:
        'You checked a scaled row by dividing it back to the row it came from, and you compared two mixes instead of two ingredient counts — that is the move the whole week rests on.',
      questionForChild: 'If a squash is mixed 2 parts cordial to 7 parts water, and I pour 6 parts of cordial, how much water goes with it — and how did you decide?',
      schoolSyncHook: 'If your child\'s class writes ratios as 3 : 5, as 3 to 5, or as a fraction, tell us and we will match the notation they use.',
    },
    vocabularyForParent: [
      'ratio (a fixed relationship between two quantities)',
      'equivalent ratios (the same relationship, both terms multiplied by the same factor)',
      'ratio table (every row is the first row taken some number of times)',
    ],
  },
});
